#include <jni.h>
#include <cstdint>
#include "stablear/vision_c.h"

namespace {
stablear_vision_tracker* ptr(jlong h){return h?reinterpret_cast<stablear_vision_tracker*>(static_cast<intptr_t>(h)):nullptr;}
stablear_xfeat_tracker* xptr(jlong h){return h?reinterpret_cast<stablear_xfeat_tracker*>(static_cast<intptr_t>(h)):nullptr;}
constexpr jsize kXFeatDescriptors=64*60*80;
constexpr jsize kXFeatReliability=60*80;
}

extern "C" JNIEXPORT jlong JNICALL Java_com_sirpaul_stablear_nativevision_NativeVision_create(JNIEnv*,jobject){auto*p=stablear_vision_create();return static_cast<jlong>(reinterpret_cast<intptr_t>(p));}
extern "C" JNIEXPORT void JNICALL Java_com_sirpaul_stablear_nativevision_NativeVision_destroy(JNIEnv*,jobject,jlong h){if(auto*p=ptr(h))stablear_vision_destroy(p);}
extern "C" JNIEXPORT jboolean JNICALL Java_com_sirpaul_stablear_nativevision_NativeVision_addRoot(JNIEnv*e,jobject,jlong h,jlong id,jbyteArray gray,jint w,jint ht,jdouble x,jdouble y){auto*p=ptr(h);if(!p||!gray||e->GetArrayLength(gray)!=w*ht)return JNI_FALSE;jbyte*b=e->GetByteArrayElements(gray,nullptr);if(!b)return JNI_FALSE;int ok=stablear_vision_add_root(p,id,reinterpret_cast<uint8_t*>(b),w,ht,x,y);e->ReleaseByteArrayElements(gray,b,JNI_ABORT);return ok?JNI_TRUE:JNI_FALSE;}
extern "C" JNIEXPORT jboolean JNICALL Java_com_sirpaul_stablear_nativevision_NativeVision_beginFrame(JNIEnv*e,jobject,jlong h,jlong id,jbyteArray gray,jint w,jint ht){auto*p=ptr(h);if(!p||!gray||e->GetArrayLength(gray)!=w*ht)return JNI_FALSE;jbyte*b=e->GetByteArrayElements(gray,nullptr);if(!b)return JNI_FALSE;int ok=stablear_vision_begin_frame(p,id,reinterpret_cast<uint8_t*>(b),w,ht);e->ReleaseByteArrayElements(gray,b,JNI_ABORT);return ok?JNI_TRUE:JNI_FALSE;}
extern "C" JNIEXPORT jdoubleArray JNICALL Java_com_sirpaul_stablear_nativevision_NativeVision_track(JNIEnv*e,jobject,jlong h,jlong id,jboolean has,jdouble x,jdouble y){auto*p=ptr(h);if(!p)return nullptr;stablear_vision_match m{};if(!stablear_vision_track(p,id,has?1:0,x,y,&m))return nullptr;jdouble v[6]{m.x,m.y,(double)m.inliers,m.median_reprojection_px,m.forward_backward_px,(double)m.method};auto a=e->NewDoubleArray(6);if(a)e->SetDoubleArrayRegion(a,0,6,v);return a;}
extern "C" JNIEXPORT void JNICALL Java_com_sirpaul_stablear_nativevision_NativeVision_remove(JNIEnv*,jobject,jlong h,jlong id){if(auto*p=ptr(h))stablear_vision_remove(p,id);}
extern "C" JNIEXPORT void JNICALL Java_com_sirpaul_stablear_nativevision_NativeVision_clear(JNIEnv*,jobject,jlong h){if(auto*p=ptr(h))stablear_vision_clear(p);}

extern "C" JNIEXPORT jlong JNICALL Java_com_sirpaul_stablear_nativevision_NativeXFeat_create(JNIEnv*,jobject){auto*p=stablear_xfeat_create();return static_cast<jlong>(reinterpret_cast<intptr_t>(p));}
extern "C" JNIEXPORT void JNICALL Java_com_sirpaul_stablear_nativevision_NativeXFeat_destroy(JNIEnv*,jobject,jlong h){if(auto*p=xptr(h))stablear_xfeat_destroy(p);}
extern "C" JNIEXPORT jboolean JNICALL Java_com_sirpaul_stablear_nativevision_NativeXFeat_addRoot(JNIEnv*e,jobject,jlong h,jlong id,jfloatArray d,jfloatArray r,jdouble x,jdouble y){auto*p=xptr(h);if(!p||!d||!r||e->GetArrayLength(d)!=kXFeatDescriptors||e->GetArrayLength(r)!=kXFeatReliability)return JNI_FALSE;jfloat*dp=e->GetFloatArrayElements(d,nullptr);jfloat*rp=e->GetFloatArrayElements(r,nullptr);if(!dp||!rp){if(dp)e->ReleaseFloatArrayElements(d,dp,JNI_ABORT);if(rp)e->ReleaseFloatArrayElements(r,rp,JNI_ABORT);return JNI_FALSE;}int ok=stablear_xfeat_add_root(p,id,dp,rp,80,60,640,480,x,y);e->ReleaseFloatArrayElements(d,dp,JNI_ABORT);e->ReleaseFloatArrayElements(r,rp,JNI_ABORT);return ok?JNI_TRUE:JNI_FALSE;}
extern "C" JNIEXPORT jboolean JNICALL Java_com_sirpaul_stablear_nativevision_NativeXFeat_addTemplate(JNIEnv*e,jobject,jlong h,jlong id,jfloatArray d,jfloatArray r,jdouble x,jdouble y,jboolean has,jdouble vx,jdouble vy,jdouble vz,jdouble scale,jdouble quality){auto*p=xptr(h);if(!p||!d||!r||e->GetArrayLength(d)!=kXFeatDescriptors||e->GetArrayLength(r)!=kXFeatReliability)return JNI_FALSE;jfloat*dp=e->GetFloatArrayElements(d,nullptr);jfloat*rp=e->GetFloatArrayElements(r,nullptr);if(!dp||!rp){if(dp)e->ReleaseFloatArrayElements(d,dp,JNI_ABORT);if(rp)e->ReleaseFloatArrayElements(r,rp,JNI_ABORT);return JNI_FALSE;}int ok=stablear_xfeat_add_template(p,id,dp,rp,80,60,640,480,x,y,has?1:0,vx,vy,vz,scale,quality);e->ReleaseFloatArrayElements(d,dp,JNI_ABORT);e->ReleaseFloatArrayElements(r,rp,JNI_ABORT);return ok?JNI_TRUE:JNI_FALSE;}
extern "C" JNIEXPORT jboolean JNICALL Java_com_sirpaul_stablear_nativevision_NativeXFeat_beginFrame(JNIEnv*e,jobject,jlong h,jlong frame,jfloatArray d,jfloatArray r){auto*p=xptr(h);if(!p||!d||!r||e->GetArrayLength(d)!=kXFeatDescriptors||e->GetArrayLength(r)!=kXFeatReliability)return JNI_FALSE;jfloat*dp=e->GetFloatArrayElements(d,nullptr);jfloat*rp=e->GetFloatArrayElements(r,nullptr);if(!dp||!rp){if(dp)e->ReleaseFloatArrayElements(d,dp,JNI_ABORT);if(rp)e->ReleaseFloatArrayElements(r,rp,JNI_ABORT);return JNI_FALSE;}int ok=stablear_xfeat_begin_frame(p,frame,dp,rp,80,60,640,480);e->ReleaseFloatArrayElements(d,dp,JNI_ABORT);e->ReleaseFloatArrayElements(r,rp,JNI_ABORT);return ok?JNI_TRUE:JNI_FALSE;}
extern "C" JNIEXPORT jdoubleArray JNICALL Java_com_sirpaul_stablear_nativevision_NativeXFeat_track(JNIEnv*e,jobject,jlong h,jlong id,jdouble x,jdouble y,jboolean has,jdouble vx,jdouble vy,jdouble vz,jdouble scale,jdouble quality){auto*p=xptr(h);if(!p)return nullptr;stablear_xfeat_match m{};if(!stablear_xfeat_track(p,id,x,y,has?1:0,vx,vy,vz,scale,quality,&m))return nullptr;jdouble v[11]{m.image.x,m.image.y,(double)m.image.inliers,m.image.median_reprojection_px,m.score,m.second_best_score,m.score_margin,m.mean_reliability,m.sigma_px,(double)m.template_serial,(double)m.image.method};auto a=e->NewDoubleArray(11);if(a)e->SetDoubleArrayRegion(a,0,11,v);return a;}
extern "C" JNIEXPORT jlong JNICALL Java_com_sirpaul_stablear_nativevision_NativeXFeat_stageTemplate(JNIEnv*,jobject,jlong h,jlong id,jdouble x,jdouble y,jboolean has,jdouble vx,jdouble vy,jdouble vz,jdouble scale,jdouble quality){auto*p=xptr(h);if(!p)return 0;return static_cast<jlong>(stablear_xfeat_stage_template(p,id,x,y,has?1:0,vx,vy,vz,scale,quality));}
extern "C" JNIEXPORT jboolean JNICALL Java_com_sirpaul_stablear_nativevision_NativeXFeat_commitStagedTemplate(JNIEnv*,jobject,jlong h,jlong id,jlong token){auto*p=xptr(h);if(!p||token<=0)return JNI_FALSE;return stablear_xfeat_commit_staged_template(p,id,static_cast<uint64_t>(token))?JNI_TRUE:JNI_FALSE;}
extern "C" JNIEXPORT void JNICALL Java_com_sirpaul_stablear_nativevision_NativeXFeat_discardStagedTemplate(JNIEnv*,jobject,jlong h,jlong id,jlong token){if(auto*p=xptr(h);p&&token>0)stablear_xfeat_discard_staged_template(p,id,static_cast<uint64_t>(token));}
extern "C" JNIEXPORT void JNICALL Java_com_sirpaul_stablear_nativevision_NativeXFeat_remove(JNIEnv*,jobject,jlong h,jlong id){if(auto*p=xptr(h))stablear_xfeat_remove(p,id);}
extern "C" JNIEXPORT void JNICALL Java_com_sirpaul_stablear_nativevision_NativeXFeat_clear(JNIEnv*,jobject,jlong h){if(auto*p=xptr(h))stablear_xfeat_clear(p);}
