#include <jni.h>
#include <cstdint>
#include <map>
#include <memory>
#include <string>
#include <vector>
#include "stablear/stablear_c.h"

namespace {
struct Bridge {
    JavaVM* vm{}; jobject store{}; jmethodID create_id{},locate_id{},destroy_id{}; stablear_session* session{};
    std::map<uint64_t,stablear_frame_ref> frames;
};
JNIEnv* envFor(Bridge* b){JNIEnv* e=nullptr;if(!b||!b->vm||b->vm->GetEnv(reinterpret_cast<void**>(&e),JNI_VERSION_1_6)!=JNI_OK)return nullptr;return e;}
bool clean(JNIEnv* e){if(e&&e->ExceptionCheck()){e->ExceptionClear();return false;}return true;}
uint64_t anchorCreate(void* c,const stablear_rigid* p){auto*b=static_cast<Bridge*>(c);JNIEnv*e=envFor(b);if(!e||!p)return 0;jdouble v[7]{p->t.x,p->t.y,p->t.z,p->q.x,p->q.y,p->q.z,p->q.w};jdoubleArray a=e->NewDoubleArray(7);if(!a)return 0;e->SetDoubleArrayRegion(a,0,7,v);jlong id=e->CallLongMethod(b->store,b->create_id,a);e->DeleteLocalRef(a);return clean(e)?static_cast<uint64_t>(id):0;}
int anchorLocate(void* c,uint64_t id,stablear_rigid* out){auto*b=static_cast<Bridge*>(c);JNIEnv*e=envFor(b);if(!e||!out)return 0;auto a=static_cast<jdoubleArray>(e->CallObjectMethod(b->store,b->locate_id,static_cast<jlong>(id)));if(!clean(e)||!a)return 0;if(e->GetArrayLength(a)!=7){e->DeleteLocalRef(a);return 0;}jdouble v[7]{};e->GetDoubleArrayRegion(a,0,7,v);e->DeleteLocalRef(a);if(!clean(e))return 0;*out={{v[0],v[1],v[2]},{v[3],v[4],v[5],v[6]}};return 1;}
void anchorDestroy(void* c,uint64_t id){auto*b=static_cast<Bridge*>(c);JNIEnv*e=envFor(b);if(!e)return;e->CallVoidMethod(b->store,b->destroy_id,static_cast<jlong>(id));clean(e);}
Bridge* bridge(jlong h){return h?reinterpret_cast<Bridge*>(static_cast<intptr_t>(h)):nullptr;}
bool pose7(JNIEnv*e,jdoubleArray a,stablear_rigid& out){if(!e||!a||e->GetArrayLength(a)!=7)return false;jdouble v[7]{};e->GetDoubleArrayRegion(a,0,7,v);if(!clean(e))return false;out={{v[0],v[1],v[2]},{v[3],v[4],v[5],v[6]}};return true;}
bool k4(JNIEnv*e,jdoubleArray a,jint w,jint h,stablear_intrinsics& out){if(!e||!a||e->GetArrayLength(a)!=4||w<=0||h<=0)return false;jdouble v[4]{};e->GetDoubleArrayRegion(a,0,4,v);if(!clean(e))return false;out={v[0],v[1],v[2],v[3],w,h};return true;}
jdoubleArray doubles(JNIEnv*e,const double*v,jsize n){auto a=e->NewDoubleArray(n);if(a)e->SetDoubleArrayRegion(a,0,n,v);return a;}
std::string utf(JNIEnv*e,jstring s){if(!s)return{};const char*p=e->GetStringUTFChars(s,nullptr);if(!p)return{};std::string out(p);e->ReleaseStringUTFChars(s,p);return out;}
int verifyConst(void* c,const uint8_t*,size_t,const uint8_t*,size_t){return *static_cast<bool*>(c)?1:0;}
}

extern "C" JNIEXPORT jlong JNICALL Java_com_sirpaul_stablear_nativeandroid_NativeStableAr_create(JNIEnv*e,jobject,jobject store){if(!e||!store)return 0;auto b=std::make_unique<Bridge>();if(e->GetJavaVM(&b->vm)!=JNI_OK)return 0;b->store=e->NewGlobalRef(store);if(!b->store)return 0;jclass cls=e->GetObjectClass(store);if(!cls)return 0;b->create_id=e->GetMethodID(cls,"create","([D)J");b->locate_id=e->GetMethodID(cls,"locate","(J)[D");b->destroy_id=e->GetMethodID(cls,"destroy","(J)V");e->DeleteLocalRef(cls);if(!clean(e)||!b->create_id||!b->locate_id||!b->destroy_id){e->DeleteGlobalRef(b->store);return 0;}stablear_anchor_callbacks cb{b.get(),anchorCreate,anchorLocate,anchorDestroy};b->session=stablear_session_create(cb,stablear_default_session_config());if(!b->session){e->DeleteGlobalRef(b->store);return 0;}return static_cast<jlong>(reinterpret_cast<intptr_t>(b.release()));}
extern "C" JNIEXPORT void JNICALL Java_com_sirpaul_stablear_nativeandroid_NativeStableAr_destroy(JNIEnv*e,jobject,jlong h){std::unique_ptr<Bridge>b(bridge(h));if(!b)return;if(b->session)stablear_session_destroy(b->session);if(e&&b->store)e->DeleteGlobalRef(b->store);}
extern "C" JNIEXPORT jlong JNICALL Java_com_sirpaul_stablear_nativeandroid_NativeStableAr_epoch(JNIEnv*,jobject,jlong h){auto*b=bridge(h);return b&&b->session?static_cast<jlong>(stablear_session_epoch(b->session)):0;}
extern "C" JNIEXPORT jlong JNICALL Java_com_sirpaul_stablear_nativeandroid_NativeStableAr_capture(JNIEnv*e,jobject,jlong h,jdoubleArray pose,jdoubleArray k,jint w,jint ht,jlong ts){auto*b=bridge(h);if(!b||!b->session||ts<=0)return 0;stablear_rigid p{};stablear_intrinsics in{};if(!pose7(e,pose,p)||!k4(e,k,w,ht,in))return 0;stablear_frame_ref f{};if(!stablear_session_capture(b->session,&p,&in,ts,nullptr,0,&f))return 0;b->frames[f.id]=f;while(b->frames.size()>256)b->frames.erase(b->frames.begin());return static_cast<jlong>(f.id);}
extern "C" JNIEXPORT jboolean JNICALL Java_com_sirpaul_stablear_nativeandroid_NativeStableAr_freeze(JNIEnv*,jobject,jlong h,jlong id){auto*b=bridge(h);if(!b||!b->session||id<=0)return JNI_FALSE;stablear_frame_ref f{};if(!stablear_session_freeze(b->session,id,&f))return JNI_FALSE;b->frames[f.id]=f;return JNI_TRUE;}
extern "C" JNIEXPORT void JNICALL Java_com_sirpaul_stablear_nativeandroid_NativeStableAr_unfreeze(JNIEnv*,jobject,jlong h,jlong id){auto*b=bridge(h);if(b&&b->session&&id>0)stablear_session_unfreeze(b->session,id);}
extern "C" JNIEXPORT jlong JNICALL Java_com_sirpaul_stablear_nativeandroid_NativeStableAr_place(JNIEnv*e,jobject,jlong h,jlong frameId,jdoubleArray depth4,jintArray origins,jlongArray evidence,jdouble x,jdouble y){auto*b=bridge(h);if(!b||!b->session)return 0;auto fi=b->frames.find(frameId);if(fi==b->frames.end()||!depth4||!origins||!evidence)return 0;jsize dl=e->GetArrayLength(depth4),n=e->GetArrayLength(origins);if(dl!=n*4||e->GetArrayLength(evidence)!=n)return 0;std::vector<jdouble>d(dl);std::vector<jint>o(n);std::vector<jlong>t(n);e->GetDoubleArrayRegion(depth4,0,dl,d.data());e->GetIntArrayRegion(origins,0,n,o.data());e->GetLongArrayRegion(evidence,0,n,t.data());if(!clean(e))return 0;std::vector<stablear_depth_sample> samples(n);for(jsize i=0;i<n;++i)samples[i]={{d[4*i],d[4*i+1]},d[4*i+2],d[4*i+3],o[i],t[i]};stablear_attachment_snapshot a{};if(!stablear_session_place(b->session,&fi->second,samples.data(),samples.size(),{x,y},&a))return 0;return static_cast<jlong>(a.id);}
extern "C" JNIEXPORT jlongArray JNICALL Java_com_sirpaul_stablear_nativeandroid_NativeStableAr_contextIds(JNIEnv*e,jobject,jlong h,jlong id,jlong frameId){auto*b=bridge(h);if(!b||!b->session)return nullptr;auto f=b->frames.find(frameId);if(f==b->frames.end())return nullptr;stablear_rigid p{};uint64_t gen=0,anchor=0;if(!stablear_session_context(b->session,id,&f->second,&p,&gen,&anchor))return nullptr;jlong v[2]{static_cast<jlong>(gen),static_cast<jlong>(anchor)};auto a=e->NewLongArray(2);if(a)e->SetLongArrayRegion(a,0,2,v);return a;}
extern "C" JNIEXPORT jdoubleArray JNICALL Java_com_sirpaul_stablear_nativeandroid_NativeStableAr_contextPose(JNIEnv*e,jobject,jlong h,jlong id,jlong frameId){auto*b=bridge(h);if(!b||!b->session)return nullptr;auto f=b->frames.find(frameId);if(f==b->frames.end())return nullptr;stablear_rigid p{};uint64_t gen=0,anchor=0;if(!stablear_session_context(b->session,id,&f->second,&p,&gen,&anchor))return nullptr;double v[7]{p.t.x,p.t.y,p.t.z,p.q.x,p.q.y,p.q.z,p.q.w};return doubles(e,v,7);}
extern "C" JNIEXPORT jint JNICALL Java_com_sirpaul_stablear_nativeandroid_NativeStableAr_observe(JNIEnv*e,jobject,jlong h,jlong id,jlong frameId,jlong epoch,jlong anchor,jlong generation,jlong cameraTs,jlong capturedNs,jdoubleArray pose,jdoubleArray k,jint w,jint ht,jdouble x,jdouble y,jint inliers,jdouble fb,jdouble reproj,jdouble sigma){auto*b=bridge(h);if(!b||!b->session)return 0;stablear_rigid p{};stablear_intrinsics in{};if(!pose7(e,pose,p)||!k4(e,k,w,ht,in))return 0;stablear_visual_observation o{static_cast<uint64_t>(frameId),static_cast<uint64_t>(epoch),static_cast<uint64_t>(anchor),static_cast<uint64_t>(generation),cameraTs,capturedNs,p,in,{x,y},inliers,fb,reproj,sigma};stablear_attachment_snapshot s{};int accepted=0;if(!stablear_session_observe(b->session,id,&o,&s,&accepted))return 0;return accepted?1:0;}
extern "C" JNIEXPORT jdoubleArray JNICALL Java_com_sirpaul_stablear_nativeandroid_NativeStableAr_worldPoint(JNIEnv*e,jobject,jlong h,jlong id){auto*b=bridge(h);stablear_v3 p{};if(!b||!b->session||!stablear_session_world_point(b->session,id,&p))return nullptr;double v[3]{p.x,p.y,p.z};return doubles(e,v,3);}
extern "C" JNIEXPORT jdoubleArray JNICALL Java_com_sirpaul_stablear_nativeandroid_NativeStableAr_initialWorldPoint(JNIEnv*e,jobject,jlong h,jlong id){auto*b=bridge(h);stablear_v3 p{};if(!b||!b->session||!stablear_session_initial_world_point(b->session,id,&p))return nullptr;double v[3]{p.x,p.y,p.z};return doubles(e,v,3);}
extern "C" JNIEXPORT jdoubleArray JNICALL Java_com_sirpaul_stablear_nativeandroid_NativeStableAr_snapshot(JNIEnv*e,jobject,jlong h,jlong id){auto*b=bridge(h);stablear_attachment_snapshot s{};if(!b||!b->session||!stablear_session_snapshot(b->session,id,&s))return nullptr;double v[5]{static_cast<double>(s.generation),s.depth_m,s.conditional_sigma_m,static_cast<double>(s.state),s.travel_m};return doubles(e,v,5);}
extern "C" JNIEXPORT void JNICALL Java_com_sirpaul_stablear_nativeandroid_NativeStableAr_visibility(JNIEnv*,jobject,jlong h,jlong id,jboolean visible,jboolean lost){auto*b=bridge(h);if(b&&b->session)stablear_session_visibility(b->session,id,visible?1:0,lost?1:0);}
extern "C" JNIEXPORT void JNICALL Java_com_sirpaul_stablear_nativeandroid_NativeStableAr_remove(JNIEnv*,jobject,jlong h,jlong id){auto*b=bridge(h);if(b&&b->session)stablear_session_remove(b->session,id);}
extern "C" JNIEXPORT void JNICALL Java_com_sirpaul_stablear_nativeandroid_NativeStableAr_trackingLost(JNIEnv*,jobject,jlong h){auto*b=bridge(h);if(b&&b->session)stablear_session_tracking_lost(b->session);}
extern "C" JNIEXPORT void JNICALL Java_com_sirpaul_stablear_nativeandroid_NativeStableAr_reset(JNIEnv*,jobject,jlong h){auto*b=bridge(h);if(b&&b->session){stablear_session_reset(b->session);b->frames.clear();}}
extern "C" JNIEXPORT jlong JNICALL Java_com_sirpaul_stablear_nativeandroid_NativeStableAr_monotonicNowNs(JNIEnv*,jobject){return stablear_monotonic_now_ns();}
extern "C" JNIEXPORT jint JNICALL Java_com_sirpaul_stablear_nativeandroid_NativeStableAr_entitlementClaimsStatus(JNIEnv*e,jobject,jstring token,jstring product,jstring platform,jstring app,jstring feature,jlong now,jboolean signatureValid){std::string t=utf(e,token),p=utf(e,product),pl=utf(e,platform),a=utf(e,app),f=utf(e,feature);if(t.empty()||p.empty()||pl.empty()||a.empty())return 0;bool valid=signatureValid==JNI_TRUE;auto r=stablear_entitlement_verify(t.c_str(),p.c_str(),pl.c_str(),a.c_str(),f.c_str(),now,&valid,verifyConst);return r.usable?(r.in_grace?2:1):0;}
