#include "stablear/stablear_c.h"
#include <math.h>
#include <stdio.h>
#include <string.h>
typedef struct {uint64_t next; stablear_rigid pose[32]; int alive[32];} store;
static uint64_t create(void*ctx,const stablear_rigid*p){store*s=(store*)ctx;uint64_t id=++s->next;if(id>=32)return 0;s->pose[id]=*p;s->alive[id]=1;return id;}
static int locate(void*ctx,uint64_t id,stablear_rigid*out){store*s=(store*)ctx;if(id>=32||!s->alive[id])return 0;*out=s->pose[id];return 1;}
static void destroy(void*ctx,uint64_t id){store*s=(store*)ctx;if(id<32)s->alive[id]=0;}
static int verify_sig(void*ctx,const uint8_t*input,size_t n,const uint8_t*sig,size_t sn){(void)ctx;(void)input;(void)n;return sn==3&&sig[0]=='s'&&sig[1]=='i'&&sig[2]=='g';}
int main(void){if(stablear_abi_version()!=1||stablear_monotonic_now_ns()<=0)return 9;stablear_v3 nullp;if(stablear_session_epoch(NULL)!=0||stablear_session_world_point(NULL,1,&nullp)!=0||stablear_session_snapshot(NULL,1,NULL)!=0)return 11;store st={0};stablear_anchor_callbacks cb={&st,create,locate,destroy};stablear_session_config cfg=stablear_default_session_config();stablear_session*s=stablear_session_create(cb,cfg);if(!s)return 1;stablear_rigid cam={{0,0,0},{0,0,0,1}};stablear_intrinsics k={800,800,320,240,640,480};stablear_depth_sample d[121];int n=0;for(int y=-10;y<=10;y+=2)for(int x=-10;x<=10;x+=2)d[n++]=(stablear_depth_sample){{320+x,240+y},2,1,0,1};stablear_frame_ref f;if(!stablear_session_capture(s,&cam,&k,1,d,n,&f))return 2;stablear_attachment_snapshot a;if(!stablear_session_place(s,&f,d,n,(stablear_v2){320,240},&a))return 3;stablear_v3 p;if(!stablear_session_world_point(s,a.id,&p)||fabs(p.z-2)>1e-5)return 4;stablear_session_remove(s,a.id);if(stablear_session_world_point(s,a.id,&p))return 5;stablear_session_destroy(s);const char* token="STABLEAR1.cHJvZHVjdF9pZD1zdGFibGVhcgpjdXN0b21lcl9pZD1hY21lCmFwcF9pZD1jb20uYWNtZS5hcHAKcGxhdGZvcm09YW5kcm9pZApmZWF0dXJlcz10cmFja2luZwpuYmY9MTAwCmV4cD0yMDAKZ3JhY2U9MTAK.c2ln";stablear_entitlement_result er=stablear_entitlement_verify(token,"stablear","android","com.acme.app","tracking",150,NULL,verify_sig);if(!er.usable)return 10;printf("PASS: C ABI smoke %s\n",stablear_version());return 0;}
