export function adminPage() {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Spatial AR · Operator</title>
<style>
:root{color-scheme:dark;--bg:#17181a;--surface:#222428;--raised:#2a2d31;--text:#f2efe8;--muted:#b9b3a9;--line:#3a3c41;--accent:#d59a4a;--blue:#7895b2;--error:#d36b60;--stale:#777b82}
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:var(--bg);color:var(--text);font:14px Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}button,input,select{font:inherit}button,select,input{background:var(--surface);color:var(--text);border:1px solid var(--line);padding:10px 12px;border-radius:6px}button{cursor:pointer}button:hover{border-color:var(--accent)}button.primary{background:var(--accent);border-color:var(--accent);color:#19150f;font-weight:750}button.quiet{background:transparent}.hidden{display:none!important}.mono{font-family:ui-monospace,SFMono-Regular,Consolas,monospace}.dim{color:var(--muted)}.amber{color:var(--accent)}.blue{color:var(--blue)}.red{color:var(--error)}
.app{min-height:100vh;display:grid;grid-template-rows:auto 1fr}header{display:flex;align-items:center;gap:12px;padding:15px 20px;border-bottom:1px solid var(--line);background:#1b1c1f;flex-wrap:wrap}header h1{font-size:19px;margin:0;font-weight:750;letter-spacing:-.02em}header .sub{color:var(--muted);font-size:12px;margin-right:auto}.server-chip{font-size:11px;color:var(--muted);max-width:300px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.conn{font-size:12px;color:var(--muted)}.conn.ok{color:var(--blue)}.conn.error{color:var(--error)}
main{display:grid;grid-template-columns:minmax(265px,325px) 1fr;min-height:0}.sidebar{border-right:1px solid var(--line);padding:18px;overflow:auto;background:#1b1c1f}.sidebar h2,.inspector h2{font-size:13px;margin:0 0 10px;color:var(--text);font-weight:700}.label{display:block;color:var(--muted);font-size:11px;margin:13px 0 5px}.sidebar select{width:100%}.map-state{margin:16px 0;padding-top:14px;border-top:1px solid var(--line)}.map-title{font-size:20px;font-weight:750;line-height:1.15}.map-id{color:var(--muted);font:11px ui-monospace,SFMono-Regular,Consolas,monospace;margin-top:4px;word-break:break-all}.statusline{display:flex;gap:8px;align-items:center;margin-top:11px}.statusmark{width:8px;height:8px;border-radius:50%;background:var(--stale)}.statusmark.ready{background:var(--blue)}.statusmark.warn{background:var(--accent)}.facts{margin-top:15px;display:grid;gap:8px}.fact{display:flex;justify-content:space-between;gap:12px;border-bottom:1px solid #2d2f33;padding-bottom:7px}.fact span:first-child{color:var(--muted)}.note{font-size:11px;line-height:1.45;color:var(--muted);margin-top:18px}.errorbox{color:var(--error);font-size:12px;line-height:1.4;margin-top:10px}.share-row{display:flex;gap:8px;margin-top:14px}.share-row button{flex:1}
.workspace{display:grid;grid-template-rows:minmax(430px,1fr) auto;min-width:0;min-height:0}.viewer{position:relative;min-height:430px;background:#121315;overflow:hidden}.viewer canvas{width:100%;height:100%;display:block;touch-action:none}.toolbar{position:absolute;left:14px;top:14px;display:flex;gap:6px;background:rgba(23,24,26,.9);padding:6px;border:1px solid var(--line);border-radius:6px}.toolbar button.active{border-color:var(--accent);color:var(--accent)}.viewer-state{position:absolute;left:18px;bottom:16px;max-width:min(620px,calc(100% - 36px));background:rgba(23,24,26,.92);border-left:3px solid var(--accent);padding:10px 12px;color:var(--muted);font-size:12px}.legend{position:absolute;right:16px;bottom:16px;background:rgba(23,24,26,.92);padding:9px 11px;border:1px solid var(--line);font-size:11px;display:grid;gap:5px}.legend-row{display:flex;align-items:center;gap:7px}.swatch{width:8px;height:8px;border-radius:50%}.swatch.point{background:#8f9298}.swatch.anchor{background:var(--accent)}.swatch.client{background:var(--blue)}.swatch.track{background:var(--error)}.swatch.stale{background:var(--stale)}
.inspector{border-top:1px solid var(--line);padding:15px 18px 18px;background:var(--surface);display:grid;grid-template-columns:1fr 1fr 1fr;gap:24px;max-height:310px;overflow:auto}.table{display:grid;gap:0}.tr{display:grid;grid-template-columns:minmax(80px,1.3fr) .8fr .8fr 1fr;gap:10px;padding:7px 0;border-bottom:1px solid var(--line);align-items:center;font-size:12px}.tr.head{color:var(--muted);font-size:10px}.tr.five{grid-template-columns:minmax(74px,1.2fr) .7fr .8fr .8fr .8fr}
.modal-backdrop{position:fixed;inset:0;background:rgba(0,0,0,.68);display:flex;align-items:center;justify-content:center;padding:18px;z-index:50}.modal{width:min(520px,100%);background:var(--surface);border:1px solid var(--line);border-radius:10px;padding:22px;box-shadow:0 24px 80px rgba(0,0,0,.4)}.modal h2{font-size:22px;margin:0 0 7px}.modal p{color:var(--muted);line-height:1.5;margin:6px 0 14px}.modal input{width:100%;margin:7px 0}.modal-actions{display:flex;gap:8px;margin-top:14px;flex-wrap:wrap}.modal-actions button{flex:1;min-width:120px}.auth-help{font-size:11px;color:var(--muted);line-height:1.45}.auth-error{min-height:18px;color:var(--error);font-size:12px;margin-top:8px}.qr-wrap{display:flex;justify-content:center;background:#f2efe8;padding:12px;border-radius:8px;margin:14px auto;width:min(360px,100%)}.qr-wrap img{width:100%;height:auto;display:block}.invite-text{font-size:11px;word-break:break-all;background:#18191b;border:1px solid var(--line);padding:10px;border-radius:6px;color:var(--muted);max-height:100px;overflow:auto}.check{display:flex;gap:8px;align-items:center;color:var(--muted);font-size:12px;margin-top:6px}.check input{width:auto;margin:0}
@media(max-width:850px){main{grid-template-columns:1fr}.sidebar{border-right:0;border-bottom:1px solid var(--line)}.workspace{grid-template-rows:500px auto}.inspector{grid-template-columns:1fr;max-height:none}.legend{display:none}}
</style>
</head>
<body>
<div class="app">
<header><h1>Spatial AR</h1><span class="sub">Operator / spatial debugger</span><span id="serverChip" class="server-chip">Discovering server…</span><span id="connection" class="conn">Locked</span><button id="ownerAccess" class="quiet">Owner access</button><button id="refresh" class="quiet">Refresh</button></header>
<main>
<aside class="sidebar">
<label class="label" for="mapSelect">Shared place</label><select id="mapSelect" disabled><option>Connect as owner first</option></select>
<div id="mapState" class="map-state"><div class="dim">The operator dashboard is owner-only. Participants do not need this token.</div></div>
<div id="shareRow" class="share-row hidden"><button id="sharePlace" class="primary">Share place QR</button></div>
<div id="sidebarError" class="errorbox"></div>
<div class="note">Sparse SAC1 points are diagnostic geometry, not a photorealistic world model. Anchor markers use the stored shared-site transform. The server cannot independently know an ARCore anchor's physical world pose; a device must resolve the Cloud Anchor.</div>
</aside>
<section class="workspace">
<div class="viewer"><canvas id="scene"></canvas><div class="toolbar"><button id="mode3d" class="active">3D</button><button id="mode2d">Top-down</button><button id="fit">Fit</button></div><div id="viewerState" class="viewer-state">Connect with the owner admin token to inspect maps.</div><div class="legend"><div class="legend-row"><span class="swatch point"></span>scan point</div><div class="legend-row"><span class="swatch anchor"></span>anchor</div><div class="legend-row"><span class="swatch client"></span>participant</div><div class="legend-row"><span class="swatch track"></span>live track</div><div class="legend-row"><span class="swatch stale"></span>stale</div></div></div>
<div class="inspector"><section><h2>Anchors</h2><div id="anchors" class="table"><div class="dim">No map selected.</div></div></section><section><h2>Participants</h2><div id="clients" class="table"><div class="dim">No live session.</div></div></section><section><h2>Tracks</h2><div id="tracks" class="table"><div class="dim">No live tracks.</div></div></section></div>
</section>
</main>
</div>

<div id="authGate" class="modal-backdrop">
  <div class="modal">
    <h2>Connect as server owner</h2>
    <p id="authServer">Checking this Spatial AR server…</p>
    <label class="label" for="token">Owner admin token</label>
    <input id="token" type="password" placeholder="sar_admin_…" autocomplete="current-password">
    <div class="auth-help">This dashboard needs the <b>owner admin token</b>. A place invite key beginning with <span class="mono">sar_map_</span> is intentionally not accepted here. Participants only need the QR/invite for the one place you share with them.</div>
    <label class="check"><input id="remember" type="checkbox"> Remember owner token in this browser</label>
    <div id="authError" class="auth-error"></div>
    <div class="modal-actions"><button id="connect" class="primary">Connect</button><button id="closeAuth" class="quiet">Close</button></div>
  </div>
</div>

<div id="shareModal" class="modal-backdrop hidden">
  <div class="modal">
    <h2 id="shareTitle">Share place</h2>
    <p>Scan this QR in Spatial AR on another phone. It contains only this place's server address, server ID, map ID and map key — never the owner admin token.</p>
    <div class="qr-wrap"><img id="inviteQr" alt="Spatial AR place invite QR"></div>
    <div id="inviteText" class="invite-text"></div>
    <div id="shareError" class="auth-error"></div>
    <div class="modal-actions"><button id="copyInvite" class="primary">Copy invite</button><button id="nativeShare">Share…</button><button id="closeShare" class="quiet">Close</button></div>
  </div>
</div>

<script>
const $=id=>document.getElementById(id);
const state={server:null,maps:[],map:null,cloud:null,live:{clients:[],tracks:[],serverTimeMs:0},mode:'3d',yaw:-.65,pitch:.42,zoom:1,drag:null,authenticated:false,invite:null};
const sessionKey='spatialOwnerToken';const storedKey='spatialOwnerTokenRemembered';
function token(){return sessionStorage.getItem(sessionKey)||localStorage.getItem(storedKey)||''}
function setToken(value,remember){sessionStorage.setItem(sessionKey,value);if(remember)localStorage.setItem(storedKey,value);else localStorage.removeItem(storedKey)}
function clearToken(){sessionStorage.removeItem(sessionKey);localStorage.removeItem(storedKey)}
function headers(){const value=token();return value?{'Authorization':'Bearer '+value}:{}}
async function request(path,options){const opts=Object.assign({},options||{});opts.headers=Object.assign({},headers(),opts.headers||{});const r=await fetch(path,opts);if(!r.ok){let body=await r.text();let message='HTTP '+r.status;try{const parsed=JSON.parse(body);message=parsed.error&&parsed.error.message?parsed.error.message:message}catch{}const e=new Error(message);e.status=r.status;throw e}return r}
async function get(path){return (await request(path)).json()}
function esc(v){return String(v==null?'':v).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function short(v){v=String(v||'');return v.length>18?v.slice(0,8)+'…'+v.slice(-6):v}
function age(ms){if(!Number.isFinite(ms))return '—';if(ms<1000)return Math.max(0,Math.round(ms))+' ms';if(ms<60000)return (ms/1000).toFixed(1)+' s';return Math.floor(ms/60000)+' m'}
function friendlyAuth(error){if(error&&error.status===401)return 'That is not the owner admin token. Use the sar_admin_… token from this server, not a sar_map_… invite key.';return error&&error.message?error.message:'Could not connect.'}

async function discover(){try{state.server=await (await fetch('/api/v1/info')).json();$('serverChip').textContent=state.server.serverName+' · '+short(state.server.serverId);$('authServer').textContent=state.server.serverName+' · '+state.server.serverId;const hash=new URLSearchParams(location.hash.replace(/^#/,''));const injected=hash.get('admin')||hash.get('token');if(injected){setToken(injected,false);history.replaceState(null,'',location.pathname+location.search)}const existing=token();if(existing){$('token').value=existing;$('remember').checked=Boolean(localStorage.getItem(storedKey));await connectOwner(true)}}catch(e){$('serverChip').textContent='Server info unavailable';$('authError').textContent=e.message}}
async function connectOwner(silent){const value=$('token').value.trim()||token();if(!value){if(!silent)$('authError').textContent='Enter the owner admin token.';return}setToken(value,$('remember').checked);$('authError').textContent='';$('connection').textContent='Connecting…';$('connection').className='conn';try{state.authenticated=true;await refreshMaps();$('authGate').classList.add('hidden');$('connection').textContent='Owner connected';$('connection').className='conn ok';$('mapSelect').disabled=false}catch(e){state.authenticated=false;clearToken();$('connection').textContent='Owner auth required';$('connection').className='conn error';$('authGate').classList.remove('hidden');$('authError').textContent=friendlyAuth(e)}}

async function refreshMaps(){state.maps=(await get('/api/v1/maps')).maps||[];const sel=$('mapSelect');const previous=state.map&&state.map.id;sel.innerHTML=state.maps.length?state.maps.map(m=>'<option value="'+esc(m.id)+'">'+esc(m.name)+' · '+esc(m.status)+'</option>').join(''):'<option value="">No maps</option>';state.map=state.maps.find(m=>m.id===previous)||state.maps[0]||null;if(state.map)sel.value=state.map.id;renderMapState();if(state.map){await Promise.all([loadGeometry(),refreshLive()])}else{state.cloud=null;state.live={clients:[],tracks:[],serverTimeMs:Date.now()};renderLive();draw()}}
function renderMapState(){const m=state.map;if(!m){$('mapState').innerHTML='<div class="dim">No maps on this server.</div>';$('shareRow').classList.add('hidden');return}const scan=m.scan||{};const hosted=(m.anchors||[]).filter(a=>a.status==='HOSTED').length;const bad=(m.anchors||[]).filter(a=>a.status==='FAILED'||a.status==='NEEDS_RESCAN').length;const cls=m.status==='READY'?'ready':'warn';$('mapState').innerHTML='<div class="map-title">'+esc(m.name)+'</div><div class="map-id">'+esc(m.id)+'</div><div class="statusline"><span class="statusmark '+cls+'"></span><b>'+esc(m.status)+'</b></div><div class="facts"><div class="fact"><span>Server geometry</span><b>'+Number(scan.pointCount||0).toLocaleString()+' points</b></div><div class="fact"><span>Scan chunks</span><b>'+Number(scan.chunkCount||0).toLocaleString()+'</b></div><div class="fact"><span>Hosted anchors</span><b>'+hosted+'</b></div><div class="fact"><span>Anchor issues</span><b class="'+(bad?'amber':'')+'">'+bad+'</b></div></div>';$('shareRow').classList.remove('hidden');renderAnchors()}
function renderAnchors(){const anchors=state.map&&state.map.anchors||[];$('anchors').innerHTML='<div class="tr head"><span>Anchor</span><span>Status</span><span>Quality</span><span>Error</span></div>'+anchors.map(a=>{const bad=a.status==='FAILED'||a.status==='NEEDS_RESCAN';const err=a.lastError||'—';return '<div class="tr"><span class="mono">'+esc(short(a.id))+'</span><span class="'+(bad?'amber':'blue')+'">'+esc(a.status||'UNKNOWN')+'</span><span>'+esc(a.featureQuality||'UNKNOWN')+'</span><span class="'+(bad?'amber':'dim')+'" title="'+esc(err)+'">'+esc(short(err))+'</span></div>'}).join('');if(!anchors.length)$('anchors').innerHTML+='<div class="dim" style="padding:9px 0">No anchors in this map.</div>'}
async function loadGeometry(){const m=state.map;if(!m)return;$('viewerState').textContent='Loading sparse geometry…';try{state.cloud=await get('/api/v1/maps/'+encodeURIComponent(m.id)+'/point-cloud?maxPoints=18000');$('sidebarError').textContent='';fitView();draw();$('viewerState').textContent=(state.cloud.sampledPoints||0).toLocaleString()+' displayed of '+(state.cloud.totalPoints||0).toLocaleString()+' server points · '+(m.anchors||[]).length+' anchors'}catch(e){state.cloud=null;$('sidebarError').textContent='Geometry: '+e.message;$('viewerState').textContent='Geometry unavailable. Live state remains usable.';draw()}}
async function refreshLive(){const m=state.map;if(!m||!state.authenticated)return;try{state.live=await get('/api/v1/maps/'+encodeURIComponent(m.id)+'/live-state');$('connection').textContent='Owner connected';$('connection').className='conn ok';renderLive();draw()}catch(e){$('connection').textContent='API error';$('connection').className='conn error';$('sidebarError').textContent=e.message}}
function renderLive(){const now=state.live.serverTimeMs||Date.now();const clients=state.live.clients||[];const tracks=state.live.tracks||[];const newestBySource=new Map();for(const t of tracks){const ts=t.serverReceivedAtMs||0;if(ts>(newestBySource.get(t.sourceId)||0))newestBySource.set(t.sourceId,ts)}$('clients').innerHTML='<div class="tr five head"><span>Device</span><span>Role</span><span>State</span><span>Last pose</span><span>Last track</span></div>'+clients.map(c=>{const poseAge=c.pose?now-c.pose.serverReceivedAtMs:Infinity;const trackTs=newestBySource.get(c.clientId)||0;const trackAge=trackTs?Math.max(0,now-trackTs):Infinity;const stale=poseAge>5000;const s=c.status&&c.status.state?c.status.state:(c.pose&&c.pose.tracking?c.pose.tracking:'connected');return '<div class="tr five"><span class="mono">'+esc(short(c.clientId))+'</span><span>'+esc(c.role)+'</span><span class="'+(stale?'dim':'blue')+'">'+esc(s)+'</span><span class="'+(stale?'dim':'')+'">'+age(poseAge)+'</span><span class="'+(trackAge>3000?'dim':'red')+'">'+age(trackAge)+'</span></div>'}).join('');if(!clients.length)$('clients').innerHTML+='<div class="dim" style="padding:9px 0">No live participants.</div>';$('tracks').innerHTML='<div class="tr head"><span>Object</span><span>Source</span><span>Confidence</span><span>Age</span></div>'+tracks.map(t=>{const a=Math.max(0,now-(t.serverReceivedAtMs||now));const stale=a>2500;return '<div class="tr"><span class="'+(stale?'dim':'red')+'">'+esc(t.label)+'</span><span class="mono">'+esc(short(t.sourceId))+'</span><span>'+Math.round((t.confidence||0)*100)+'%</span><span class="'+(stale?'dim':'')+'">'+age(a)+'</span></div>'}).join('');if(!tracks.length)$('tracks').innerHTML+='<div class="dim" style="padding:9px 0">No live tracks.</div>'}

async function openShare(){const m=state.map;if(!m)return;$('shareModal').classList.remove('hidden');$('shareTitle').textContent='Share '+m.name;$('inviteQr').removeAttribute('src');$('inviteText').textContent='Loading invite…';$('shareError').textContent='';try{const payload=await get('/api/v1/maps/'+encodeURIComponent(m.id)+'/invite');state.invite=payload.invite;const svg=await (await request('/api/v1/maps/'+encodeURIComponent(m.id)+'/invite-qr.svg')).text();$('inviteQr').src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg);$('inviteText').textContent=state.invite.deepLink||''}catch(e){$('shareError').textContent=e.message}}
async function copyInvite(){if(!state.invite||!state.invite.deepLink)return;try{await navigator.clipboard.writeText(state.invite.deepLink);$('shareError').textContent='Copied.';$('shareError').style.color='var(--blue)'}catch(e){$('shareError').textContent='Copy failed: '+e.message;$('shareError').style.color='var(--error)'}}
async function nativeShare(){if(!state.invite||!state.invite.deepLink)return;if(navigator.share){try{await navigator.share({title:'Spatial AR place',text:state.invite.deepLink})}catch{}}else copyInvite()}

const canvas=$('scene'),ctx=canvas.getContext('2d');function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);canvas.width=Math.max(1,Math.floor(r.width*d));canvas.height=Math.max(1,Math.floor(r.height*d));ctx.setTransform(d,0,0,d,0,0);draw()}new ResizeObserver(resize).observe(canvas);
function bounds(){return state.cloud&&state.cloud.bounds?state.cloud.bounds:{min:[-5,-2,-5],max:[5,2,5]}}
function fitView(){state.zoom=1;state.yaw=-.65;state.pitch=.42;draw()}
function project(p,w,h){const b=bounds(),cx=(b.min[0]+b.max[0])/2,cy=(b.min[1]+b.max[1])/2,cz=(b.min[2]+b.max[2])/2;let x=p[0]-cx,y=p[1]-cy,z=p[2]-cz;const span=Math.max(1,b.max[0]-b.min[0],b.max[2]-b.min[2],b.max[1]-b.min[1]);const scale=Math.min(w,h)*.78/span*state.zoom;if(state.mode==='2d')return[w/2+x*scale,h/2+z*scale,1];const ca=Math.cos(state.yaw),sa=Math.sin(state.yaw),cp=Math.cos(state.pitch),sp=Math.sin(state.pitch);const rx=x*ca-z*sa,rz=x*sa+z*ca,ry=y*cp-rz*sp,depth=y*sp+rz*cp;return[w/2+rx*scale,h/2-ry*scale,depth]}
function anchorPos(a){const t=a.siteFromAnchor||[];return t.length>=15?[Number(t[12])||0,Number(t[13])||0,Number(t[14])||0]:null}
function drawDot(p,r,fill,stroke){const w=canvas.clientWidth,h=canvas.clientHeight,q=project(p,w,h);ctx.beginPath();ctx.arc(q[0],q[1],r,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke()}}
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);ctx.fillStyle='#121315';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#24262a';ctx.lineWidth=1;for(let i=1;i<10;i++){ctx.beginPath();ctx.moveTo(i*w/10,0);ctx.lineTo(i*w/10,h);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i*h/10);ctx.lineTo(w,i*h/10);ctx.stroke()}const points=state.cloud&&state.cloud.points||[];ctx.fillStyle='#85888e';for(const p of points){const q=project(p,w,h);ctx.globalAlpha=.25+.55*Math.max(0,Math.min(1,Number(p[3]||.5)));ctx.fillRect(q[0],q[1],1.35,1.35)}ctx.globalAlpha=1;for(const a of state.map&&state.map.anchors||[]){const p=anchorPos(a);if(p)drawDot(p,5,'#d59a4a','#f2efe8')}const now=state.live.serverTimeMs||Date.now();for(const c of state.live.clients||[]){if(c.pose&&c.pose.position){const stale=now-c.pose.serverReceivedAtMs>5000;drawDot(c.pose.position,5,stale?'#777b82':'#7895b2','#f2efe8')}}for(const t of state.live.tracks||[]){if(t.position){const stale=now-(t.serverReceivedAtMs||now)>2500;drawDot(t.position,6,stale?'#777b82':'#d36b60','#f2efe8')}}}
canvas.addEventListener('pointerdown',e=>{state.drag={x:e.clientX,y:e.clientY,yaw:state.yaw,pitch:state.pitch};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!state.drag||state.mode==='2d')return;state.yaw=state.drag.yaw+(e.clientX-state.drag.x)*.008;state.pitch=Math.max(-1.2,Math.min(1.2,state.drag.pitch+(e.clientY-state.drag.y)*.006));draw()});canvas.addEventListener('pointerup',()=>state.drag=null);canvas.addEventListener('wheel',e=>{e.preventDefault();state.zoom=Math.max(.25,Math.min(8,state.zoom*Math.exp(-e.deltaY*.001)));draw()},{passive:false});

$('connect').onclick=()=>connectOwner(false);$('closeAuth').onclick=()=>$('authGate').classList.add('hidden');$('ownerAccess').onclick=()=>{$('token').value=token();$('authGate').classList.remove('hidden')};$('refresh').onclick=async()=>{if(!state.authenticated){$('authGate').classList.remove('hidden');return}try{await refreshMaps();$('sidebarError').textContent=''}catch(e){$('sidebarError').textContent=e.message}};$('mapSelect').onchange=async e=>{state.map=state.maps.find(m=>m.id===e.target.value)||null;renderMapState();if(state.map)await Promise.all([loadGeometry(),refreshLive()])};$('sharePlace').onclick=openShare;$('copyInvite').onclick=copyInvite;$('nativeShare').onclick=nativeShare;$('closeShare').onclick=()=>$('shareModal').classList.add('hidden');$('mode3d').onclick=()=>{state.mode='3d';$('mode3d').classList.add('active');$('mode2d').classList.remove('active');draw()};$('mode2d').onclick=()=>{state.mode='2d';$('mode2d').classList.add('active');$('mode3d').classList.remove('active');draw()};$('fit').onclick=fitView;
setInterval(()=>{if(state.authenticated&&state.map)refreshLive()},2000);discover();resize();
</script>
</body></html>`;
}
