export function adminPage() {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Spatial AR · Operator</title>
<style>
:root{color-scheme:dark;--bg:#17181a;--surface:#222428;--raised:#2a2d31;--text:#f2efe8;--muted:#b9b3a9;--line:#3a3c41;--accent:#d59a4a;--blue:#7895b2;--error:#d36b60;--stale:#777b82}
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:var(--bg);color:var(--text);font:14px Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}button,input,select{font:inherit}button,select,input{background:var(--surface);color:var(--text);border:1px solid var(--line);padding:9px 11px;border-radius:5px}button{cursor:pointer}button:hover{border-color:var(--accent)}button.primary{background:var(--accent);border-color:var(--accent);color:#1b1711;font-weight:700}button.quiet{background:transparent}.app{min-height:100vh;display:grid;grid-template-rows:auto 1fr}
header{display:flex;align-items:center;gap:16px;padding:15px 20px;border-bottom:1px solid var(--line);background:#1b1c1f;flex-wrap:wrap}header h1{font-size:19px;margin:0;font-weight:700;letter-spacing:-.02em}header .sub{color:var(--muted);font-size:12px;margin-right:auto}.conn{font-size:12px;color:var(--muted)}.conn.ok{color:var(--blue)}.conn.error{color:var(--error)}
main{display:grid;grid-template-columns:minmax(250px,310px) 1fr;min-height:0}.sidebar{border-right:1px solid var(--line);padding:18px;overflow:auto;background:#1b1c1f}.sidebar h2,.inspector h2{font-size:13px;margin:0 0 10px;color:var(--text);font-weight:700}.label{display:block;color:var(--muted);font-size:11px;margin:13px 0 5px}.sidebar select,.sidebar input{width:100%}.map-state{margin:16px 0;padding-top:14px;border-top:1px solid var(--line)}.map-title{font-size:20px;font-weight:700;line-height:1.15}.map-id{color:var(--muted);font:11px ui-monospace,SFMono-Regular,Consolas,monospace;margin-top:4px;word-break:break-all}.statusline{display:flex;gap:8px;align-items:center;margin-top:11px}.statusmark{width:8px;height:8px;border-radius:50%;background:var(--stale)}.statusmark.ready{background:var(--blue)}.statusmark.warn{background:var(--accent)}.facts{margin-top:15px;display:grid;gap:8px}.fact{display:flex;justify-content:space-between;gap:12px;border-bottom:1px solid #2d2f33;padding-bottom:7px}.fact span:first-child{color:var(--muted)}.note{font-size:11px;line-height:1.45;color:var(--muted);margin-top:18px}.errorbox{color:var(--error);font-size:12px;line-height:1.4;margin-top:10px}
.workspace{display:grid;grid-template-rows:minmax(430px,1fr) auto;min-width:0;min-height:0}.viewer{position:relative;min-height:430px;background:#121315;overflow:hidden}.viewer canvas{width:100%;height:100%;display:block;touch-action:none}.toolbar{position:absolute;left:14px;top:14px;display:flex;gap:6px;background:rgba(23,24,26,.88);padding:6px;border:1px solid var(--line);border-radius:6px}.toolbar button.active{border-color:var(--accent);color:var(--accent)}.viewer-state{position:absolute;left:18px;bottom:16px;max-width:min(560px,calc(100% - 36px));background:rgba(23,24,26,.9);border-left:3px solid var(--accent);padding:9px 11px;color:var(--muted);font-size:12px}.legend{position:absolute;right:16px;bottom:16px;background:rgba(23,24,26,.9);padding:9px 11px;border:1px solid var(--line);font-size:11px;display:grid;gap:5px}.legend-row{display:flex;align-items:center;gap:7px}.swatch{width:8px;height:8px;border-radius:50%}.swatch.point{background:#8f9298}.swatch.anchor{background:var(--accent)}.swatch.client{background:var(--blue)}.swatch.track{background:var(--error)}.swatch.stale{background:var(--stale)}
.inspector{border-top:1px solid var(--line);padding:15px 18px 18px;background:var(--surface);display:grid;grid-template-columns:1fr 1fr;gap:24px;max-height:290px;overflow:auto}.table{display:grid;gap:0}.tr{display:grid;grid-template-columns:minmax(80px,1.3fr) .8fr .8fr 1fr;gap:10px;padding:7px 0;border-bottom:1px solid var(--line);align-items:center;font-size:12px}.tr.head{color:var(--muted);font-size:10px}.mono{font-family:ui-monospace,SFMono-Regular,Consolas,monospace}.dim{color:var(--muted)}.amber{color:var(--accent)}.blue{color:var(--blue)}.red{color:var(--error)}
@media(max-width:850px){main{grid-template-columns:1fr}.sidebar{border-right:0;border-bottom:1px solid var(--line)}.workspace{grid-template-rows:500px auto}.inspector{grid-template-columns:1fr;max-height:none}}
</style>
</head>
<body>
<div class="app">
<header><h1>Spatial AR</h1><span class="sub">Operator / spatial debugger</span><span id="connection" class="conn">Connecting</span><input id="token" type="password" placeholder="API token" autocomplete="off"><button id="save">Use token</button><button id="refresh" class="quiet">Refresh</button></header>
<main>
<aside class="sidebar">
<label class="label" for="mapSelect">Shared place</label><select id="mapSelect"><option>Loading maps…</option></select>
<div id="mapState" class="map-state"><div class="dim">Choose a map.</div></div>
<div id="sidebarError" class="errorbox"></div>
<div class="note">Sparse SAC1 points are diagnostic geometry, not a photorealistic world model. Anchor markers use the stored shared-site transform. The server cannot independently know an ARCore anchor's physical world pose; a device must resolve the Cloud Anchor.</div>
</aside>
<section class="workspace">
<div class="viewer"><canvas id="scene"></canvas><div class="toolbar"><button id="mode3d" class="active">3D</button><button id="mode2d">Top-down</button><button id="fit">Fit</button></div><div id="viewerState" class="viewer-state">Loading spatial data…</div><div class="legend"><div class="legend-row"><span class="swatch point"></span>scan point</div><div class="legend-row"><span class="swatch anchor"></span>anchor</div><div class="legend-row"><span class="swatch client"></span>participant</div><div class="legend-row"><span class="swatch track"></span>live track</div><div class="legend-row"><span class="swatch stale"></span>stale</div></div></div>
<div class="inspector"><section><h2>Participants</h2><div id="clients" class="table"></div></section><section><h2>Tracks</h2><div id="tracks" class="table"></div></section></div>
</section>
</main>
</div>
<script>
const $=id=>document.getElementById(id);const tokenEl=$('token');tokenEl.value=localStorage.spatialToken||'';
const state={maps:[],map:null,cloud:null,live:{clients:[],tracks:[],serverTimeMs:0},mode:'3d',yaw:-.65,pitch:.42,zoom:1,drag:null};
const headers=()=>tokenEl.value?{'Authorization':'Bearer '+tokenEl.value}:{};
async function get(path){const r=await fetch(path,{headers:headers()});if(!r.ok){let text=await r.text();throw new Error(r.status+' '+text.slice(0,180))}return r.json()}
function esc(v){return String(v==null?'':v).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function short(v){v=String(v||'');return v.length>18?v.slice(0,8)+'…'+v.slice(-6):v}
function age(ms){if(!Number.isFinite(ms))return '—';if(ms<1000)return ms+' ms';if(ms<60000)return (ms/1000).toFixed(1)+' s';return Math.floor(ms/60000)+' m'}
async function refreshMaps(){state.maps=(await get('/api/v1/maps')).maps||[];const sel=$('mapSelect');const previous=state.map&&state.map.id;sel.innerHTML=state.maps.length?state.maps.map(m=>'<option value="'+esc(m.id)+'">'+esc(m.name)+' · '+esc(m.status)+'</option>').join(''):'<option value="">No maps</option>';let chosen=state.maps.find(m=>m.id===previous)||state.maps[0]||null;state.map=chosen;if(chosen)sel.value=chosen.id;renderMapState();if(chosen)await loadGeometry()}
function renderMapState(){const m=state.map;if(!m){$('mapState').innerHTML='<div class="dim">No map selected.</div>';return}const scan=m.scan||{};const hosted=(m.anchors||[]).filter(a=>a.status==='HOSTED').length;const bad=(m.anchors||[]).filter(a=>a.status==='FAILED'||a.status==='NEEDS_RESCAN').length;const cls=m.status==='READY'?'ready':'warn';$('mapState').innerHTML='<div class="map-title">'+esc(m.name)+'</div><div class="map-id">'+esc(m.id)+'</div><div class="statusline"><span class="statusmark '+cls+'"></span><b>'+esc(m.status)+'</b></div><div class="facts"><div class="fact"><span>Server geometry</span><b>'+Number(scan.pointCount||0).toLocaleString()+' points</b></div><div class="fact"><span>Scan chunks</span><b>'+Number(scan.chunkCount||0).toLocaleString()+'</b></div><div class="fact"><span>Hosted anchors</span><b>'+hosted+'</b></div><div class="fact"><span>Anchor issues</span><b class="'+(bad?'amber':'')+'">'+bad+'</b></div></div>'}
async function loadGeometry(){const m=state.map;if(!m)return;$('viewerState').textContent='Loading sparse geometry…';try{state.cloud=await get('/api/v1/maps/'+encodeURIComponent(m.id)+'/point-cloud?maxPoints=18000');$('sidebarError').textContent='';fitView();draw();$('viewerState').textContent=(state.cloud.sampledPoints||0).toLocaleString()+' displayed of '+(state.cloud.totalPoints||0).toLocaleString()+' server points · '+(m.anchors||[]).length+' anchors'}catch(e){state.cloud=null;$('sidebarError').textContent='Geometry: '+e.message;$('viewerState').textContent='Geometry unavailable. Live state remains usable.';draw()}}
async function refreshLive(){const m=state.map;if(!m)return;try{state.live=await get('/api/v1/maps/'+encodeURIComponent(m.id)+'/live-state');$('connection').textContent='Server online';$('connection').className='conn ok';renderLive();draw()}catch(e){$('connection').textContent='Server/API error';$('connection').className='conn error';$('sidebarError').textContent=e.message}}
function renderLive(){const now=state.live.serverTimeMs||Date.now();const clients=state.live.clients||[];const tracks=state.live.tracks||[];$('clients').innerHTML='<div class="tr head"><span>Device</span><span>Role</span><span>State</span><span>Last pose</span></div>'+clients.map(c=>{const poseAge=c.pose?now-c.pose.serverReceivedAtMs:Infinity;const stale=poseAge>5000;const s=c.status&&c.status.state?c.status.state:(c.pose&&c.pose.trackingState?c.pose.trackingState:'connected');return '<div class="tr"><span class="mono">'+esc(short(c.clientId))+'</span><span>'+esc(c.role)+'</span><span class="'+(stale?'dim':'blue')+'">'+esc(s)+'</span><span class="'+(stale?'dim':'')+'">'+age(poseAge)+'</span></div>'}).join('');if(!clients.length)$('clients').innerHTML+='<div class="dim" style="padding:9px 0">No live participants.</div>';$('tracks').innerHTML='<div class="tr head"><span>Object</span><span>Source</span><span>Confidence</span><span>Age</span></div>'+tracks.map(t=>{const a=Math.max(0,now-(t.serverReceivedAtMs||now));const stale=a>2500;return '<div class="tr"><span class="'+(stale?'dim':'red')+'">'+esc(t.label)+'</span><span class="mono">'+esc(short(t.sourceId))+'</span><span>'+Math.round((t.confidence||0)*100)+'%</span><span class="'+(stale?'dim':'')+'">'+age(a)+'</span></div>'}).join('');if(!tracks.length)$('tracks').innerHTML+='<div class="dim" style="padding:9px 0">No live tracks.</div>'}
const canvas=$('scene'),ctx=canvas.getContext('2d');function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);canvas.width=Math.max(1,Math.floor(r.width*d));canvas.height=Math.max(1,Math.floor(r.height*d));ctx.setTransform(d,0,0,d,0,0);draw()}new ResizeObserver(resize).observe(canvas);
function bounds(){return state.cloud&&state.cloud.bounds?state.cloud.bounds:{min:[-5,-2,-5],max:[5,2,5]}}
function fitView(){state.zoom=1;state.yaw=-.65;state.pitch=.42}
function project(p,w,h){const b=bounds(),cx=(b.min[0]+b.max[0])/2,cy=(b.min[1]+b.max[1])/2,cz=(b.min[2]+b.max[2])/2;let x=p[0]-cx,y=p[1]-cy,z=p[2]-cz;const span=Math.max(1,b.max[0]-b.min[0],b.max[2]-b.min[2],b.max[1]-b.min[1]);const scale=Math.min(w,h)*.78/span*state.zoom;if(state.mode==='2d')return [w/2+x*scale,h/2+z*scale,1];const cyaw=Math.cos(state.yaw),syaw=Math.sin(state.yaw),xp=x*cyaw-z*syaw,zp=x*syaw+z*cyaw;const cp=Math.cos(state.pitch),sp=Math.sin(state.pitch),yp=y*cp-zp*sp,depth=y*sp+zp*cp;const perspective=Math.max(.48,1-depth/(span*3));return [w/2+xp*scale*perspective,h/2-yp*scale*perspective,perspective]}
function marker(p,color,r,label,w,h){const q=project(p,w,h);ctx.beginPath();ctx.arc(q[0],q[1],r,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();if(label){ctx.font='11px system-ui';ctx.fillStyle='#f2efe8';ctx.fillText(label,q[0]+r+4,q[1]-r-2)}}
function draw(){const r=canvas.getBoundingClientRect(),w=r.width,h=r.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#121315';ctx.fillRect(0,0,w,h);const pts=state.cloud&&state.cloud.points||[];ctx.fillStyle='#8f9298';for(let i=0;i<pts.length;i++){const q=project(pts[i],w,h);ctx.globalAlpha=.22+Math.min(.38,Math.max(0,pts[i][3]||0)*.3);ctx.fillRect(q[0],q[1],state.mode==='2d'?1.4:Math.max(.8,q[2]*1.25),state.mode==='2d'?1.4:Math.max(.8,q[2]*1.25))}ctx.globalAlpha=1;const m=state.map;if(m)for(const a of m.anchors||[]){const mat=a.siteFromAnchor||[];if(mat.length===16)marker([mat[12]||0,mat[13]||0,mat[14]||0],'#d59a4a',5,short(a.id),w,h)}const now=state.live.serverTimeMs||Date.now();for(const c of state.live.clients||[]){if(!c.pose||!Array.isArray(c.pose.position))continue;const stale=now-c.pose.serverReceivedAtMs>5000;marker(c.pose.position,stale?'#777b82':'#7895b2',5,short(c.clientId),w,h)}for(const t of state.live.tracks||[]){if(!Array.isArray(t.position))continue;const stale=now-(t.serverReceivedAtMs||now)>2500;marker(t.position,stale?'#777b82':'#d36b60',6,t.label,w,h)}}
canvas.addEventListener('pointerdown',e=>{state.drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!state.drag||state.mode!=='3d')return;const dx=e.clientX-state.drag[0],dy=e.clientY-state.drag[1];state.drag=[e.clientX,e.clientY];state.yaw+=dx*.007;state.pitch=Math.max(-1.2,Math.min(1.2,state.pitch+dy*.007));draw()});canvas.addEventListener('pointerup',()=>state.drag=null);canvas.addEventListener('wheel',e=>{e.preventDefault();state.zoom=Math.max(.25,Math.min(8,state.zoom*Math.exp(-e.deltaY*.001)));draw()},{passive:false});
$('mode3d').onclick=()=>{state.mode='3d';$('mode3d').className='active';$('mode2d').className='';draw()};$('mode2d').onclick=()=>{state.mode='2d';$('mode2d').className='active';$('mode3d').className='';draw()};$('fit').onclick=()=>{fitView();draw()};$('mapSelect').onchange=async e=>{state.map=state.maps.find(m=>m.id===e.target.value)||null;renderMapState();await loadGeometry();await refreshLive()};$('save').onclick=async()=>{localStorage.spatialToken=tokenEl.value;await boot()};$('refresh').onclick=boot;
async function boot(){try{$('sidebarError').textContent='';await refreshMaps();await refreshLive()}catch(e){$('connection').textContent='Server/API error';$('connection').className='conn error';$('sidebarError').textContent=e.message;$('viewerState').textContent='Unable to load spatial data.'}}
boot();setInterval(refreshLive,1500);setInterval(async()=>{try{const maps=(await get('/api/v1/maps')).maps||[];state.maps=maps;if(state.map){const updated=maps.find(m=>m.id===state.map.id);if(updated){state.map=updated;renderMapState()}}}catch{}},5000);
</script>
</body></html>`;
}
