export function adminPage() {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Spatial AR · World Debugger</title>
<style>
:root{color-scheme:dark;--bg:#101114;--surface:#181a1f;--raised:#20232a;--line:#30343c;--text:#f2efe8;--muted:#a9adb7;--amber:#d59a4a;--cyan:#62d7c7;--blue:#7895b2;--red:#df6f67;--green:#68cf83;--purple:#b88ee8}
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:var(--bg);color:var(--text);font:13px Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}button,input,select{font:inherit}button,select,input{background:var(--surface);color:var(--text);border:1px solid var(--line);padding:8px 10px;border-radius:7px}button{cursor:pointer}button:hover{border-color:var(--amber)}button.active{color:var(--amber);border-color:var(--amber)}.hidden{display:none!important}.mono{font-family:ui-monospace,SFMono-Regular,Consolas,monospace}.dim{color:var(--muted)}.ok{color:var(--cyan)}.warn{color:var(--amber)}.bad{color:var(--red)}
.app{min-height:100vh;display:grid;grid-template-rows:auto 1fr}header{display:flex;align-items:center;gap:10px;padding:12px 16px;border-bottom:1px solid var(--line);background:#14161a;flex-wrap:wrap}header h1{margin:0;font-size:18px}.grow{flex:1}.chip{font-size:11px;color:var(--muted);max-width:320px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
main{display:grid;grid-template-columns:300px 1fr;min-height:0}.sidebar{padding:14px;border-right:1px solid var(--line);background:#14161a;overflow:auto}.label{display:block;color:var(--muted);font-size:10px;margin:11px 0 5px;text-transform:uppercase;letter-spacing:.08em}.sidebar select{width:100%}.card{margin-top:12px;padding:11px;border:1px solid var(--line);border-radius:8px;background:var(--surface)}.title{font-size:18px;font-weight:750}.small{font-size:11px}.facts{display:grid;gap:6px;margin-top:10px}.fact{display:flex;justify-content:space-between;gap:10px;padding-bottom:5px;border-bottom:1px solid #292c32}.layers{display:grid;grid-template-columns:1fr 1fr;gap:7px}.layers label{display:flex;align-items:center;gap:7px;color:var(--muted);font-size:11px}.layers input{margin:0;width:auto}.help{font-size:10px;line-height:1.45;color:var(--muted);margin-top:12px}
.workspace{display:grid;grid-template-rows:minmax(500px,1fr) 260px;min-width:0;min-height:0}.viewer{position:relative;overflow:hidden;background:#0d0e11}.viewer canvas{width:100%;height:100%;display:block;touch-action:none}.toolbar{position:absolute;left:12px;top:12px;display:flex;gap:6px;padding:6px;background:rgba(16,17,20,.88);border:1px solid var(--line);border-radius:8px;backdrop-filter:blur(8px)}.hud{position:absolute;left:12px;bottom:12px;max-width:min(720px,calc(100% - 24px));padding:9px 11px;background:rgba(16,17,20,.9);border-left:3px solid var(--amber);color:var(--muted);font-size:11px}.legend{position:absolute;right:12px;bottom:12px;padding:8px 10px;background:rgba(16,17,20,.9);border:1px solid var(--line);font-size:10px;display:grid;gap:4px}.legend div{display:flex;align-items:center;gap:6px}.dot{width:8px;height:8px;border-radius:50%;display:inline-block}.inspector{border-top:1px solid var(--line);background:var(--surface);display:grid;grid-template-columns:1fr 1fr 1fr;gap:18px;padding:12px 14px;overflow:auto}.inspector h2{font-size:12px;margin:0 0 7px}.table{display:grid}.tr{display:grid;grid-template-columns:1.2fr .8fr .8fr .8fr;gap:8px;padding:5px 0;border-bottom:1px solid var(--line);align-items:center;font-size:11px}.head{color:var(--muted);font-size:9px;text-transform:uppercase}.modal-bg{position:fixed;inset:0;background:rgba(0,0,0,.72);display:flex;align-items:center;justify-content:center;z-index:40;padding:18px}.modal{width:min(500px,100%);background:var(--surface);border:1px solid var(--line);border-radius:10px;padding:18px}.modal input{width:100%;margin-top:7px}.actions{display:flex;gap:8px;margin-top:12px}.actions button{flex:1}.error{color:var(--red);font-size:11px;min-height:16px;margin-top:8px}
@media(max-width:900px){main{grid-template-columns:1fr}.sidebar{border-right:0;border-bottom:1px solid var(--line)}.workspace{grid-template-rows:520px auto}.inspector{grid-template-columns:1fr}.legend{display:none}}
</style>
</head>
<body>
<div class="app">
<header><h1>Spatial AR · World Debugger</h1><span class="chip" id="serverChip">Discovering server…</span><span id="connection" class="chip grow">Locked</span><button id="ownerAccess">Owner access</button><button id="refresh">Refresh</button></header>
<main>
<aside class="sidebar">
<label class="label">Shared place</label><select id="mapSelect" disabled><option>Connect as owner first</option></select>
<div id="mapCard" class="card"><span class="dim">Owner authentication required.</span></div>
<div class="card"><div class="label" style="margin-top:0">Layers</div><div class="layers">
<label><input type="checkbox" data-layer="points" checked> Point cloud</label>
<label><input type="checkbox" data-layer="terrain" checked> Terrain</label>
<label><input type="checkbox" data-layer="anchors" checked> Anchors + axes</label>
<label><input type="checkbox" data-layer="clients" checked> Clients</label>
<label><input type="checkbox" data-layer="clientTrails" checked> Client trails</label>
<label><input type="checkbox" data-layer="tracks" checked> 3D tracks</label>
<label><input type="checkbox" data-layer="trackTrails" checked> Track trails</label>
<label><input type="checkbox" data-layer="velocity" checked> Velocity</label>
<label><input type="checkbox" data-layer="uncertainty" checked> Uncertainty</label>
<label><input type="checkbox" data-layer="labels" checked> Labels</label>
</div></div>
<div class="card"><div class="label" style="margin-top:0">Derived terrain</div><div id="terrainStats" class="small dim">Waiting for scan geometry.</div></div>
<div class="help">Cloud Anchors give us a stable shared pose after resolve plus host/resolve state and feature-map quality. ARCore does not expose the Cloud Anchor service's internal visual feature map for download. The terrain surface shown here is therefore derived from your own uploaded SAC1 sparse XYZ scan, not from Google's private Cloud Anchor map.</div>
</aside>
<section class="workspace">
<div class="viewer"><canvas id="scene"></canvas><div class="toolbar"><button id="mode3d" class="active">3D orbit</button><button id="mode2d">Top-down</button><button id="fit">Fit</button><button id="pause">Pause live</button></div><div id="hud" class="hud">Connect as owner to inspect the shared world.</div><div class="legend"><div><span class="dot" style="background:#85888e"></span>scan</div><div><span class="dot" style="background:var(--green)"></span>terrain</div><div><span class="dot" style="background:var(--amber)"></span>anchor</div><div><span class="dot" style="background:var(--cyan)"></span>client</div><div><span class="dot" style="background:var(--red)"></span>track</div></div></div>
<div class="inspector"><section><h2>Cloud anchors</h2><div id="anchors" class="table"></div></section><section><h2>Participants</h2><div id="clients" class="table"></div></section><section><h2>Live objects · spatial provenance</h2><div id="tracks" class="table"></div></section></div>
</section>
</main>
</div>
<div id="authGate" class="modal-bg"><div class="modal"><h2>Server owner access</h2><div class="dim">Use the server owner token (<span class="mono">sar_admin_…</span>), not a place invite key.</div><input id="token" type="password" placeholder="sar_admin_…"><label style="display:flex;gap:7px;align-items:center;margin-top:8px;color:var(--muted);font-size:11px"><input id="remember" type="checkbox" style="width:auto;margin:0"> Remember in this browser</label><div id="authError" class="error"></div><div class="actions"><button id="connect">Connect</button><button id="closeAuth">Close</button></div></div></div>
<script>
const $=id=>document.getElementById(id);
const state={server:null,maps:[],map:null,cloud:null,terrain:[],live:{clients:[],tracks:[],serverTimeMs:0},mode:'3d',yaw:-.72,pitch:.48,zoom:1,drag:null,authenticated:false,paused:false,layers:{points:true,terrain:true,anchors:true,clients:true,clientTrails:true,tracks:true,trackTrails:true,velocity:true,uncertainty:true,labels:true},clientTrails:new Map(),trackTrails:new Map()};
const sessionKey='spatialOwnerToken',storedKey='spatialOwnerTokenRemembered';
const token=()=>sessionStorage.getItem(sessionKey)||localStorage.getItem(storedKey)||'';
function setToken(v,remember){sessionStorage.setItem(sessionKey,v);if(remember)localStorage.setItem(storedKey,v);else localStorage.removeItem(storedKey)}
function headers(){const v=token();return v?{'Authorization':'Bearer '+v}:{}}
async function req(path){const r=await fetch(path,{headers:headers()});if(!r.ok){const text=await r.text();let m='HTTP '+r.status;try{m=JSON.parse(text).error?.message||m}catch{}const e=new Error(m);e.status=r.status;throw e}return r}
async function get(path){return (await req(path)).json()}
function esc(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function short(v,n=14){v=String(v||'');return v.length>n?v.slice(0,6)+'…'+v.slice(-5):v}
function age(ms){if(!Number.isFinite(ms))return '—';if(ms<1000)return Math.max(0,Math.round(ms))+'ms';if(ms<60000)return (ms/1000).toFixed(1)+'s';return Math.floor(ms/60000)+'m'}
function v3(a){return Array.isArray(a)&&a.length>=3?[+a[0]||0,+a[1]||0,+a[2]||0]:[0,0,0]}
function add(a,b){return[a[0]+b[0],a[1]+b[1],a[2]+b[2]]}function sub(a,b){return[a[0]-b[0],a[1]-b[1],a[2]-b[2]]}function mul(a,s){return[a[0]*s,a[1]*s,a[2]*s]}
function rotateQuat(v,q){if(!Array.isArray(q)||q.length<4)return v;const x=+q[0]||0,y=+q[1]||0,z=+q[2]||0,w=+q[3]||1;const tx=2*(y*v[2]-z*v[1]),ty=2*(z*v[0]-x*v[2]),tz=2*(x*v[1]-y*v[0]);return[v[0]+w*tx+(y*tz-z*ty),v[1]+w*ty+(z*tx-x*tz),v[2]+w*tz+(x*ty-y*tx)]}
async function discover(){try{state.server=await (await fetch('/api/v1/info')).json();$('serverChip').textContent=state.server.serverName+' · '+short(state.server.serverId,20);if(token()){$('token').value=token();$('remember').checked=Boolean(localStorage.getItem(storedKey));await connectOwner(true)}}catch(e){$('serverChip').textContent=e.message}}
async function connectOwner(silent=false){const v=$('token').value.trim()||token();if(!v){if(!silent)$('authError').textContent='Enter owner token.';return}setToken(v,$('remember').checked);try{state.authenticated=true;await refreshMaps();$('authGate').classList.add('hidden');$('mapSelect').disabled=false;$('connection').textContent='Owner connected';$('connection').className='chip grow ok'}catch(e){state.authenticated=false;$('connection').textContent='Owner auth required';$('connection').className='chip grow bad';$('authError').textContent=e.message;$('authGate').classList.remove('hidden')}}
async function refreshMaps(){state.maps=(await get('/api/v1/maps')).maps||[];const prev=state.map?.id;state.map=state.maps.find(m=>m.id===prev)||state.maps[0]||null;const s=$('mapSelect');s.innerHTML=state.maps.length?state.maps.map(m=>'<option value="'+esc(m.id)+'">'+esc(m.name)+' · '+esc(m.status)+'</option>').join(''):'<option>No maps</option>';if(state.map)s.value=state.map.id;renderMap();if(state.map)await Promise.all([loadGeometry(),refreshLive()])}
function renderMap(){const m=state.map;if(!m){$('mapCard').innerHTML='<span class="dim">No map.</span>';return}const scan=m.scan||{},hosted=(m.anchors||[]).filter(a=>a.status==='HOSTED').length;$('mapCard').innerHTML='<div class="title">'+esc(m.name)+'</div><div class="mono small dim">'+esc(m.id)+'</div><div class="facts"><div class="fact"><span>State</span><b>'+esc(m.status)+'</b></div><div class="fact"><span>Scan</span><b>'+Number(scan.pointCount||0).toLocaleString()+' pts</b></div><div class="fact"><span>Chunks</span><b>'+Number(scan.chunkCount||0)+'</b></div><div class="fact"><span>Hosted anchors</span><b>'+hosted+'</b></div><div class="fact"><span>Legacy groundY</span><b>'+(m.groundY==null?'—':Number(m.groundY).toFixed(2)+' m')+'</b></div></div>';renderTables()}
async function loadGeometry(){const m=state.map;if(!m)return;$('hud').textContent='Loading shared scan geometry…';try{state.cloud=await get('/api/v1/maps/'+encodeURIComponent(m.id)+'/point-cloud?maxPoints=50000');deriveTerrain();fitView()}catch(e){state.cloud=null;state.terrain=[];$('hud').textContent='Geometry unavailable: '+e.message}draw()}
function deriveTerrain(){const pts=state.cloud?.points||[];if(!pts.length){state.terrain=[];$('terrainStats').textContent='No scan points.';return}const b=state.cloud.bounds,spanX=Math.max(.1,b.max[0]-b.min[0]),spanZ=Math.max(.1,b.max[2]-b.min[2]);const cell=Math.max(.25,Math.min(.65,Math.max(spanX,spanZ)/80));const bins=new Map();for(const p of pts){const ix=Math.floor(p[0]/cell),iz=Math.floor(p[2]/cell),k=ix+','+iz;let a=bins.get(k);if(!a)bins.set(k,a=[]);if((p[3]??0)>=.25)a.push(p[1])}const out=[];for(const [k,ys] of bins){if(ys.length<2)continue;ys.sort((a,b)=>a-b);const q=ys[Math.min(ys.length-1,Math.floor(ys.length*.18))];const [ix,iz]=k.split(',').map(Number);out.push([ (ix+.5)*cell,q,(iz+.5)*cell,Math.min(1,ys.length/12) ])}state.terrain=out;$('terrainStats').innerHTML='<b>'+out.length.toLocaleString()+'</b> cells · '+cell.toFixed(2)+'m grid<br><span class="dim">robust low-quantile surface from SAC1 XYZ; diagnostic, not semantic ground classification</span>'}
function appendTrail(map,key,pos,at,max=120){if(!pos)return;let arr=map.get(key);if(!arr)map.set(key,arr=[]);const last=arr[arr.length-1];if(!last||at-last.t>180||Math.hypot(pos[0]-last.p[0],pos[1]-last.p[1],pos[2]-last.p[2])>.03)arr.push({p:[...pos],t:at});while(arr.length>max)arr.shift();while(arr.length&&at-arr[0].t>30000)arr.shift()}
async function refreshLive(){if(!state.authenticated||!state.map||state.paused)return;try{state.live=await get('/api/v1/maps/'+encodeURIComponent(state.map.id)+'/live-state');const now=state.live.serverTimeMs||Date.now();for(const c of state.live.clients||[])if(c.pose?.position)appendTrail(state.clientTrails,c.clientId,v3(c.pose.position),c.pose.serverReceivedAtMs||now);for(const t of state.live.tracks||[])if(t.position)appendTrail(state.trackTrails,t.key||((t.sourceId||'')+':'+(t.id||'')),v3(t.position),t.serverReceivedAtMs||now);renderTables();draw();$('connection').textContent='Live · '+(state.live.clients||[]).length+' clients · '+(state.live.tracks||[]).length+' tracks';$('connection').className='chip grow ok'}catch(e){$('connection').textContent='Live API: '+e.message;$('connection').className='chip grow bad'}}
function renderTables(){const m=state.map,now=state.live.serverTimeMs||Date.now();const anchors=m?.anchors||[];$('anchors').innerHTML='<div class="tr head"><span>Anchor</span><span>Status</span><span>Quality</span><span>Y</span></div>'+anchors.map(a=>{const p=anchorPos(a);return'<div class="tr"><span class="mono">'+esc(short(a.id))+'</span><span class="'+(a.status==='HOSTED'?'ok':'warn')+'">'+esc(a.status)+'</span><span>'+esc(a.featureQuality||'UNKNOWN')+'</span><span>'+(p?p[1].toFixed(2):'—')+'</span></div>'}).join('');const clients=state.live.clients||[];$('clients').innerHTML='<div class="tr head"><span>Client</span><span>Role</span><span>Tracking</span><span>Pose age</span></div>'+clients.map(c=>{const a=c.pose?now-c.pose.serverReceivedAtMs:Infinity;return'<div class="tr"><span class="mono">'+esc(short(c.clientId))+'</span><span>'+esc(c.role)+'</span><span class="'+(a<3000?'ok':'dim')+'">'+esc(c.pose?.tracking||c.status?.state||'connected')+'</span><span>'+age(a)+'</span></div>'}).join('');const tracks=state.live.tracks||[];$('tracks').innerHTML='<div class="tr head"><span>Track</span><span>Source</span><span>Confidence</span><span>Age</span></div>'+tracks.map(t=>{const a=now-(t.serverReceivedAtMs||now);return'<div class="tr"><span class="'+(a<2500?'bad':'dim')+'" title="'+esc((t.spatialMethod||'unknown')+' · terrainY '+(t.terrainY==null?'—':Number(t.terrainY).toFixed(2))+' · depth '+(t.depthConfidence==null?'—':Math.round(t.depthConfidence*100)+'%')+' · hits '+Number(t.hitCount||0))+'">'+esc(t.label)+' · '+esc(short(t.id,10))+' · '+esc(t.spatialMethod||'unknown')+'</span><span class="mono">'+esc(short(t.sourceId))+'</span><span>'+Math.round((t.confidence||0)*100)+'% · h'+Number(t.hitCount||0)+'</span><span>'+age(a)+'</span></div>'}).join('')}
const canvas=$('scene'),ctx=canvas.getContext('2d');function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);canvas.width=Math.max(1,Math.floor(r.width*d));canvas.height=Math.max(1,Math.floor(r.height*d));ctx.setTransform(d,0,0,d,0,0);draw()}new ResizeObserver(resize).observe(canvas);
function bounds(){return state.cloud?.bounds||{min:[-5,-2,-5],max:[5,2,5]}}function fitView(){state.zoom=1;state.yaw=-.72;state.pitch=.48;draw()}
function project(p,w=canvas.clientWidth,h=canvas.clientHeight){const b=bounds(),cx=(b.min[0]+b.max[0])/2,cy=(b.min[1]+b.max[1])/2,cz=(b.min[2]+b.max[2])/2;let x=p[0]-cx,y=p[1]-cy,z=p[2]-cz;const span=Math.max(1,b.max[0]-b.min[0],b.max[2]-b.min[2],b.max[1]-b.min[1]);const scale=Math.min(w,h)*.78/span*state.zoom;if(state.mode==='2d')return[w/2+x*scale,h/2+z*scale,0];const ca=Math.cos(state.yaw),sa=Math.sin(state.yaw),cp=Math.cos(state.pitch),sp=Math.sin(state.pitch),rx=x*ca-z*sa,rz=x*sa+z*ca,ry=y*cp-rz*sp,depth=y*sp+rz*cp;return[w/2+rx*scale,h/2-ry*scale,depth]}
function line3(a,b,color,width=1,alpha=1){const A=project(a),B=project(b);ctx.globalAlpha=alpha;ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(A[0],A[1]);ctx.lineTo(B[0],B[1]);ctx.stroke();ctx.globalAlpha=1}
function dot3(p,r,color,stroke){const q=project(p);ctx.beginPath();ctx.arc(q[0],q[1],r,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}return q}
function label3(p,text,color='#f2efe8'){if(!state.layers.labels)return;const q=project(p);ctx.font='11px ui-monospace,monospace';const w=ctx.measureText(text).width+10;ctx.fillStyle='rgba(10,11,14,.84)';ctx.fillRect(q[0]+7,q[1]-17,w,18);ctx.fillStyle=color;ctx.fillText(text,q[0]+12,q[1]-5)}
function anchorPos(a){const t=a.siteFromAnchor||[];return t.length===16?[+t[12]||0,+t[13]||0,+t[14]||0]:null}function axisFromMatrix(a,local){const m=a.siteFromAnchor||[];if(m.length!==16)return null;return[m[12]+m[0]*local[0]+m[4]*local[1]+m[8]*local[2],m[13]+m[1]*local[0]+m[5]*local[1]+m[9]*local[2],m[14]+m[2]*local[0]+m[6]*local[1]+m[10]*local[2]]}
function drawTrail(arr,color){if(!arr||arr.length<2)return;for(let i=1;i<arr.length;i++){const f=i/(arr.length-1);line3(arr[i-1].p,arr[i].p,color,1.4,.12+.65*f)}}
function drawClient(c,now){if(!c.pose?.position)return;const p=v3(c.pose.position),stale=now-c.pose.serverReceivedAtMs>4000,col=stale?'#676b73':'#62d7c7';if(state.layers.clientTrails)drawTrail(state.clientTrails.get(c.clientId),col);dot3(p,5,col,'#f2efe8');const q=c.pose.rotation||[0,0,0,1],right=add(p,rotateQuat([.45,0,0],q)),up=add(p,rotateQuat([0,.45,0],q)),forward=add(p,rotateQuat([0,0,-.75],q));line3(p,right,'#df6f67',2);line3(p,up,'#68cf83',2);line3(p,forward,'#7895ff',2);const f=rotateQuat([0,0,-.35],q),r=rotateQuat([.20,0,-.30],q),l=rotateQuat([-.20,0,-.30],q),u=rotateQuat([0,.14,-.30],q);line3(add(p,f),add(p,r),col,1.2);line3(add(p,f),add(p,l),col,1.2);line3(add(p,f),add(p,u),col,1.2);line3(add(p,r),add(p,l),col,1);label3(add(p,[0,.18,0]),'phone '+short(c.clientId)+' '+(c.pose.tracking||''),col)}
function cornersForTrack(t){const p=v3(t.position),e=v3(t.extentMeters||[.6,.6,.6]),hx=e[0]/2,hy=e[1],hz=e[2]/2,yaw=+(t.yawRadians||0),c=Math.cos(yaw),s=Math.sin(yaw);const out=[];for(const y of [0,hy])for(const z of [-hz,hz])for(const x of [-hx,hx])out.push([p[0]+x*c-z*s,p[1]+y,p[2]+x*s+z*c]);return out}
function drawTrack(t,now){if(!t.position)return;const key=t.key||((t.sourceId||'')+':'+(t.id||'')),ageMs=now-(t.serverReceivedAtMs||now),col=ageMs>2500?'#676b73':'#df6f67';if(state.layers.trackTrails)drawTrail(state.trackTrails.get(key),col);const p=v3(t.position),c=cornersForTrack(t),edges=[[0,1],[0,2],[0,4],[1,3],[1,5],[2,3],[2,6],[3,7],[4,5],[4,6],[5,7],[6,7]];for(const e of edges)line3(c[e[0]],c[e[1]],col,1.4,.85);dot3(p,3,col);if(state.layers.velocity&&t.velocity){const v=v3(t.velocity),mag=Math.hypot(...v);if(mag>.03)line3(add(p,[0,.12,0]),add(add(p,[0,.12,0]),mul(v,Math.min(1,1/Math.max(.1,mag)))), '#b88ee8',2)}if(state.layers.uncertainty){const r=Math.max(.05,Math.min(3,+t.uncertaintyMeters||.5));for(let i=0;i<24;i++){const a=i*Math.PI*2/24,b=(i+1)*Math.PI*2/24;line3([p[0]+Math.cos(a)*r,p[1]+.02,p[2]+Math.sin(a)*r],[p[0]+Math.cos(b)*r,p[1]+.02,p[2]+Math.sin(b)*r],col,1,.28)}}label3(add(p,[0,(t.extentMeters?.[1]||.6)+.12,0]),(t.label||'object')+' '+short(t.id,9)+' '+Math.round((t.confidence||0)*100)+'%',col)}
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);ctx.fillStyle='#0d0e11';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#1c1f24';for(let i=1;i<10;i++){ctx.beginPath();ctx.moveTo(i*w/10,0);ctx.lineTo(i*w/10,h);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i*h/10);ctx.lineTo(w,i*h/10);ctx.stroke()}if(state.layers.points){for(const p of state.cloud?.points||[]){const q=project(p);ctx.globalAlpha=.12+.55*Math.max(0,Math.min(1,+p[3]||.4));ctx.fillStyle='#8c9098';ctx.fillRect(q[0],q[1],1.25,1.25)}ctx.globalAlpha=1}if(state.layers.terrain){const b=bounds(),minY=b.min[1],range=Math.max(.01,b.max[1]-b.min[1]);for(const p of state.terrain){const q=project(p),f=(p[1]-minY)/range;ctx.globalAlpha=.18+.45*p[3];ctx.fillStyle='hsl('+(125+f*75)+' 45% '+(32+f*25)+'%)';ctx.fillRect(q[0]-1.5,q[1]-1.5,3,3)}ctx.globalAlpha=1}if(state.layers.anchors){for(const a of state.map?.anchors||[]){const p=anchorPos(a);if(!p)continue;dot3(p,5,'#d59a4a','#f2efe8');const x=axisFromMatrix(a,[.5,0,0]),y=axisFromMatrix(a,[0,.5,0]),z=axisFromMatrix(a,[0,0,-.5]);if(x)line3(p,x,'#df6f67',2);if(y)line3(p,y,'#68cf83',2);if(z)line3(p,z,'#7895ff',2);label3(add(p,[0,.12,0]),'anchor '+short(a.id)+' '+(a.featureQuality||''),'#d59a4a')}}const now=state.live.serverTimeMs||Date.now();if(state.layers.clients)for(const c of state.live.clients||[])drawClient(c,now);if(state.layers.tracks)for(const t of state.live.tracks||[])drawTrack(t,now);$('hud').textContent=(state.cloud?.sampledPoints||0).toLocaleString()+' scan pts / '+(state.cloud?.totalPoints||0).toLocaleString()+' total · '+state.terrain.length.toLocaleString()+' terrain cells · '+(state.map?.anchors||[]).length+' anchors · '+(state.live.clients||[]).length+' clients · '+(state.live.tracks||[]).length+' live tracks'}
canvas.addEventListener('pointerdown',e=>{state.drag={x:e.clientX,y:e.clientY,yaw:state.yaw,pitch:state.pitch};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!state.drag||state.mode==='2d')return;state.yaw=state.drag.yaw+(e.clientX-state.drag.x)*.008;state.pitch=Math.max(-1.35,Math.min(1.35,state.drag.pitch+(e.clientY-state.drag.y)*.006));draw()});canvas.addEventListener('pointerup',()=>state.drag=null);canvas.addEventListener('wheel',e=>{e.preventDefault();state.zoom=Math.max(.2,Math.min(10,state.zoom*Math.exp(-e.deltaY*.001)));draw()},{passive:false});
for(const el of document.querySelectorAll('[data-layer]'))el.onchange=()=>{state.layers[el.dataset.layer]=el.checked;draw()};$('connect').onclick=()=>connectOwner();$('closeAuth').onclick=()=>$('authGate').classList.add('hidden');$('ownerAccess').onclick=()=>{$('token').value=token();$('authGate').classList.remove('hidden')};$('refresh').onclick=()=>state.authenticated&&refreshMaps();$('mapSelect').onchange=async e=>{state.map=state.maps.find(m=>m.id===e.target.value)||null;state.clientTrails.clear();state.trackTrails.clear();renderMap();if(state.map)await Promise.all([loadGeometry(),refreshLive()])};$('mode3d').onclick=()=>{state.mode='3d';$('mode3d').classList.add('active');$('mode2d').classList.remove('active');draw()};$('mode2d').onclick=()=>{state.mode='2d';$('mode2d').classList.add('active');$('mode3d').classList.remove('active');draw()};$('fit').onclick=fitView;$('pause').onclick=()=>{state.paused=!state.paused;$('pause').textContent=state.paused?'Resume live':'Pause live';$('pause').classList.toggle('active',state.paused)};
setInterval(()=>{if(state.authenticated&&state.map&&!state.paused)refreshLive()},500);discover();resize();
</script>
</body></html>`;
}
