export function opsPage() {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Spatial Ops · Common Operating Picture</title>
<style>
:root{color-scheme:dark;--bg:#080b0e;--panel:#0e1318;--panel2:#131a20;--line:#22303a;--text:#e8edf0;--muted:#7f929e;--cyan:#4fe1d2;--green:#72e390;--amber:#f2b653;--red:#ff6f68;--blue:#6ca9ff;--violet:#b995ff}
*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:var(--bg);color:var(--text);font:12px Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}button,input,select{font:inherit;color:inherit}button,select,input[type=password]{background:var(--panel2);border:1px solid var(--line);border-radius:6px;padding:7px 9px}button{cursor:pointer}button:hover,button.active{border-color:var(--cyan);color:var(--cyan)}.mono{font-family:ui-monospace,SFMono-Regular,Consolas,monospace}.muted{color:var(--muted)}.ok{color:var(--green)}.warn{color:var(--amber)}.bad{color:var(--red)}.hidden{display:none!important}
.app{height:100vh;display:grid;grid-template-rows:52px 1fr 82px}.topbar{display:flex;align-items:center;gap:10px;padding:8px 12px;background:#0b0f13;border-bottom:1px solid var(--line)}.brand{display:flex;align-items:center;gap:9px;min-width:260px}.brandMark{width:10px;height:30px;background:linear-gradient(180deg,var(--cyan),#194f56);box-shadow:0 0 18px rgba(79,225,210,.25)}.brandTitle{font-weight:800;font-size:15px;letter-spacing:.08em}.brandSub{font-size:9px;color:var(--muted);letter-spacing:.16em}.grow{flex:1}.chip{padding:5px 8px;border:1px solid var(--line);border-radius:999px;color:var(--muted);white-space:nowrap}.chip.live{color:var(--green);border-color:#274f36}.mapSelect{min-width:220px}
.workspace{min-height:0;display:grid;grid-template-columns:270px minmax(400px,1fr) 330px}.left,.right{min-height:0;overflow:auto;background:var(--panel);padding:10px}.left{border-right:1px solid var(--line)}.right{border-left:1px solid var(--line)}.sceneWrap{position:relative;min-width:0;min-height:0;background:radial-gradient(circle at 50% 45%,#111820 0,#080b0e 72%);overflow:hidden}.sceneWrap canvas{position:absolute;inset:0;width:100%;height:100%;display:block;touch-action:none}.sceneToolbar{position:absolute;top:10px;left:10px;display:flex;gap:6px;padding:5px;border:1px solid var(--line);border-radius:7px;background:rgba(8,11,14,.88);backdrop-filter:blur(8px)}.sceneHud{position:absolute;left:12px;bottom:12px;max-width:70%;padding:8px 10px;border-left:2px solid var(--cyan);background:rgba(8,11,14,.9);color:var(--muted)}
.section{margin-bottom:12px;border:1px solid var(--line);background:#0b1014}.sectionTitle{display:flex;align-items:center;justify-content:space-between;padding:8px 9px;border-bottom:1px solid var(--line);font-size:10px;text-transform:uppercase;letter-spacing:.12em;color:#9bacb6}.sectionBody{padding:8px}.metricGrid{display:grid;grid-template-columns:1fr 1fr;gap:6px}.metric{padding:8px;background:#10171c;border:1px solid #1d2a32}.metric b{display:block;font-size:19px;line-height:1.05}.metric span{font-size:9px;color:var(--muted);text-transform:uppercase}.row{display:flex;align-items:center;gap:7px;padding:6px 0;border-bottom:1px solid #182229}.row:last-child{border-bottom:0}.row .name{min-width:0;flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.dot{width:7px;height:7px;border-radius:50%;background:var(--muted);box-shadow:0 0 7px currentColor}.dot.ok{background:var(--green)}.dot.warn{background:var(--amber)}.dot.bad{background:var(--red)}.tiny{font-size:9px;color:var(--muted)}.layers{display:grid;grid-template-columns:1fr 1fr;gap:6px}.layers label{display:flex;align-items:center;gap:6px;color:var(--muted);font-size:10px}.layers input{accent-color:var(--cyan)}
.entity{padding:8px;margin-bottom:6px;border:1px solid var(--line);background:#0d1419;cursor:pointer}.entity:hover,.entity.selected{border-color:var(--cyan);background:#101b20}.entityHead{display:flex;align-items:center;gap:7px}.entityLabel{font-weight:800;text-transform:uppercase}.quality{margin-left:auto;padding:2px 5px;border:1px solid var(--line);border-radius:4px;font-size:8px}.quality.multi{color:var(--green);border-color:#285139}.quality.conflict{color:var(--red);border-color:#5a2d2b}.entityMeta{display:flex;gap:9px;margin-top:5px;color:var(--muted);font-size:9px}.kv{display:grid;grid-template-columns:1fr auto;gap:5px 9px}.kv div:nth-child(odd){color:var(--muted)}.obs{margin-top:7px;padding:6px;border-left:2px solid #2b4850;background:#0b1115}.obsHead{display:flex;gap:6px;align-items:center}.sourceTag{font-size:8px;border:1px solid var(--line);border-radius:3px;padding:1px 4px;color:var(--cyan)}
.timeline{display:grid;grid-template-columns:260px 1fr 330px;align-items:center;gap:12px;padding:10px 12px;border-top:1px solid var(--line);background:#0b0f13}.timelineControls{display:flex;align-items:center;gap:6px}.timelineMain{min-width:0}.timelineMain input{width:100%;accent-color:var(--cyan)}.timelineLabels{display:flex;justify-content:space-between;color:var(--muted);font-size:9px;margin-top:3px}.timelineState{text-align:right;color:var(--muted)}.timelineState b{color:var(--text)}
.modalBg{position:fixed;inset:0;z-index:30;display:flex;align-items:center;justify-content:center;background:rgba(0,0,0,.72)}.modal{width:min(430px,calc(100% - 30px));padding:18px;background:var(--panel);border:1px solid var(--line)}.modal h2{margin:0 0 8px}.modal input{width:100%;margin:10px 0}.modalActions{display:flex;gap:7px}.modalActions button{flex:1}.error{min-height:16px;color:var(--red);margin-top:7px}
@media(max-width:1000px){.workspace{grid-template-columns:230px 1fr}.right{display:none}.timeline{grid-template-columns:220px 1fr}.timelineState{display:none}.brand{min-width:180px}.brandSub{display:none}}
</style>
</head>
<body>
<div class="app">
  <header class="topbar">
    <div class="brand"><div class="brandMark"></div><div><div class="brandTitle">SPATIAL OPS</div><div class="brandSub">COMMON OPERATING PICTURE</div></div></div>
    <select id="mapSelect" class="mapSelect" disabled><option>Owner access required</option></select>
    <span id="serverChip" class="chip">discovering server</span>
    <span id="modeChip" class="chip live">LIVE</span>
    <span class="grow"></span>
    <button id="worldDebugger" title="Open classic world debugger">World debugger</button>
    <button id="ownerAccess">Owner access</button>
  </header>
  <main class="workspace">
    <aside class="left">
      <section class="section"><div class="sectionTitle"><span>Fusion status</span><span id="fusionAge" class="tiny">—</span></div><div class="sectionBody"><div class="metricGrid">
        <div class="metric"><b id="metricSensors">0</b><span>sensors</span></div>
        <div class="metric"><b id="metricLocalized">0</b><span>localized</span></div>
        <div class="metric"><b id="metricRaw">0</b><span>raw observations</span></div>
        <div class="metric"><b id="metricFused">0</b><span>fused entities</span></div>
      </div><div class="row" style="margin-top:5px"><span class="dot ok"></span><span class="name">Multi-sensor confirmed</span><b id="metricMulti">0</b></div></div></section>
      <section class="section"><div class="sectionTitle"><span>Sensor mesh</span><span id="sensorCount" class="tiny">0 online</span></div><div id="sensors" class="sectionBody"></div></section>
      <section class="section"><div class="sectionTitle"><span>World layers</span></div><div class="sectionBody"><div class="layers">
        <label><input type="checkbox" data-layer="points" checked> Scan cloud</label>
        <label><input type="checkbox" data-layer="anchors" checked> Anchors</label>
        <label><input type="checkbox" data-layer="clients" checked> Sensors</label>
        <label><input type="checkbox" data-layer="links" checked> Provenance</label>
        <label><input type="checkbox" data-layer="tracks" checked> Fused tracks</label>
        <label><input type="checkbox" data-layer="uncertainty" checked> Uncertainty</label>
        <label><input type="checkbox" data-layer="trails" checked> Trails</label>
        <label><input type="checkbox" data-layer="labels" checked> Labels</label>
      </div></div></section>
      <section class="section"><div class="sectionTitle"><span>Map readiness</span></div><div id="mapFacts" class="sectionBody kv"><div>Anchors</div><b>—</b><div>Scan points</div><b>—</b><div>Replay buffer</div><b>—</b></div></section>
    </aside>
    <section class="sceneWrap">
      <canvas id="scene"></canvas>
      <div class="sceneToolbar"><button id="viewIso" class="active">Isometric</button><button id="viewTop">Top-down</button><button id="fit">Fit</button><button id="liveNow">Live</button></div>
      <div id="sceneHud" class="sceneHud">Authenticate to build the common operating picture.</div>
    </section>
    <aside class="right">
      <section class="section"><div class="sectionTitle"><span>Fused entities</span><span id="entityCount" class="tiny">0</span></div><div id="entities" class="sectionBody"></div></section>
      <section class="section"><div class="sectionTitle"><span>Entity inspector</span></div><div id="inspector" class="sectionBody"><span class="muted">Select a fused entity.</span></div></section>
    </aside>
  </main>
  <footer class="timeline">
    <div class="timelineControls"><button id="play">▶</button><button id="jumpLive">LIVE</button><span class="mono" id="replayClock">--:--:--</span></div>
    <div class="timelineMain"><input id="timeline" type="range" min="0" max="0" value="0" step="1" disabled><div class="timelineLabels"><span id="oldest">-10m</span><span id="newest">now</span></div></div>
    <div class="timelineState"><b id="timelineMode">LIVE SENSOR FUSION</b><br><span id="timelineDetail">No replay frames yet</span></div>
  </footer>
</div>
<div id="authGate" class="modalBg"><div class="modal"><h2>Owner access</h2><div class="muted">Use the server owner token. It stays in this browser only.</div><input id="token" type="password" placeholder="sar_admin_…"><label class="tiny"><input id="remember" type="checkbox"> Remember on this device</label><div id="authError" class="error"></div><div class="modalActions"><button id="connect">Connect</button><button id="closeAuth">Close</button></div></div></div>
<script>
const $=id=>document.getElementById(id);
const sessionKey='spatialOwnerToken',storedKey='spatialOwnerTokenRemembered';
const state={server:null,maps:[],map:null,cloud:null,live:null,history:[],selectedId:null,mode:'live',replayIndex:0,playing:false,view:'iso',yaw:-.65,zoom:1,center:[0,0,0],drag:null,layers:{points:true,anchors:true,clients:true,links:true,tracks:true,uncertainty:true,trails:true,labels:true}};
const token=()=>sessionStorage.getItem(sessionKey)||localStorage.getItem(storedKey)||'';
function setToken(v,remember){sessionStorage.setItem(sessionKey,v);if(remember)localStorage.setItem(storedKey,v);else localStorage.removeItem(storedKey)}
function headers(){const v=token();return v?{Authorization:'Bearer '+v}:{}}
async function get(path){const r=await fetch(path,{headers:headers()});if(!r.ok){let message='HTTP '+r.status;try{message=(await r.json()).error?.message||message}catch{}const e=new Error(message);e.status=r.status;throw e}return r.json()}
function esc(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function short(v,n=16){v=String(v||'');return v.length>n?v.slice(0,6)+'…'+v.slice(-5):v}
function age(ms){if(!Number.isFinite(ms))return '—';if(ms<1000)return Math.max(0,Math.round(ms))+'ms';if(ms<60000)return (ms/1000).toFixed(1)+'s';return Math.floor(ms/60000)+'m'}
function fmt(v,d=2){return Number.isFinite(Number(v))?Number(v).toFixed(d):'—'}
function pos(v){return Array.isArray(v)&&v.length>=3?v.map(Number):[0,0,0]}
function matrixPos(m){return Array.isArray(m)&&m.length===16?[+m[12]||0,+m[13]||0,+m[14]||0]:[0,0,0]}
function rotateQuat(v,q){if(!Array.isArray(q)||q.length<4)return v;const x=+q[0]||0,y=+q[1]||0,z=+q[2]||0,w=+q[3]||1,tx=2*(y*v[2]-z*v[1]),ty=2*(z*v[0]-x*v[2]),tz=2*(x*v[1]-y*v[0]);return[v[0]+w*tx+(y*tz-z*ty),v[1]+w*ty+(z*tx-x*tz),v[2]+w*tz+(x*ty-y*tx)]}
function currentFrame(){if(state.mode==='live'||!state.history.length)return state.live;return state.history[Math.max(0,Math.min(state.history.length-1,state.replayIndex))]||state.live}
async function discover(){try{state.server=await (await fetch('/api/v1/info')).json();$('serverChip').textContent=(state.server.serverName||'server')+' · '+short(state.server.serverId,20);if(token()){$('token').value=token();$('remember').checked=Boolean(localStorage.getItem(storedKey));await connectOwner(true)}}catch(e){$('serverChip').textContent=e.message}}
async function connectOwner(silent=false){const v=$('token').value.trim()||token();if(!v){if(!silent)$('authError').textContent='Owner token required.';return}setToken(v,$('remember').checked);try{await refreshMaps();$('authGate').classList.add('hidden')}catch(e){$('authError').textContent=e.message;$('authGate').classList.remove('hidden')}}
async function refreshMaps(){const data=await get('/api/v1/maps');state.maps=data.maps||[];const previous=state.map?.id;state.map=state.maps.find(m=>m.id===previous)||state.maps[0]||null;const select=$('mapSelect');select.disabled=false;select.innerHTML=state.maps.length?state.maps.map(m=>'<option value="'+esc(m.id)+'">'+esc(m.name)+' · '+esc(m.status)+'</option>').join(''):'<option>No maps</option>';if(state.map){select.value=state.map.id;await loadMap()}}
async function loadMap(){if(!state.map)return;state.history=[];state.live=null;state.selectedId=null;state.mode='live';$('timeline').disabled=true;try{state.cloud=await get('/api/v1/maps/'+encodeURIComponent(state.map.id)+'/point-cloud?maxPoints=30000')}catch{state.cloud=null}fitView();await Promise.all([refreshLive(),refreshReplay()]);renderAll()}
async function refreshLive(){if(!state.map)return;try{state.live=await get('/api/v1/maps/'+encodeURIComponent(state.map.id)+'/ops-state');if(state.mode==='live')renderAll()}catch(e){$('sceneHud').textContent='Ops state unavailable: '+e.message}}
async function refreshReplay(){if(!state.map)return;try{const replay=await get('/api/v1/maps/'+encodeURIComponent(state.map.id)+'/mission-replay?seconds=600&limit=1200');state.history=replay.frames||[];const slider=$('timeline');slider.max=Math.max(0,state.history.length-1);if(state.mode==='live')slider.value=slider.max;slider.disabled=state.history.length===0;renderTimeline()}catch(e){$('timelineDetail').textContent='Replay unavailable: '+e.message}}
function fitView(){const points=state.cloud?.points||[];const anchors=state.map?.anchors||[];const all=[];for(let i=0;i<points.length;i+=Math.max(1,Math.floor(points.length/2500)))all.push(points[i]);for(const a of anchors)all.push(matrixPos(a.siteFromAnchor));if(!all.length){state.center=[0,0,0];state.zoom=1;return}let min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(const p0 of all){const p=pos(p0);for(let i=0;i<3;i++){min[i]=Math.min(min[i],p[i]);max[i]=Math.max(max[i],p[i])}}state.center=[(min[0]+max[0])/2,(min[1]+max[1])/2,(min[2]+max[2])/2];const span=Math.max(5,max[0]-min[0],max[2]-min[2]);state.zoom=24/span}
function renderAll(){renderMetrics();renderSensors();renderEntities();renderInspector();renderMapFacts();renderTimeline();draw()}
function renderMetrics(){const l=currentFrame()||{clients:[],fusedTracks:[],fusion:{}};const f=l.fusion||{};$('metricSensors').textContent=f.connectedClientCount??(l.clients||[]).length;$('metricLocalized').textContent=f.localizedClientCount??(l.clients||[]).filter(c=>c.pose).length;$('metricRaw').textContent=f.rawObservationCount??l.rawTrackCount??(l.tracks||[]).length;$('metricFused').textContent=f.fusedEntityCount??(l.fusedTracks||[]).length;$('metricMulti').textContent=f.multiSensorEntityCount??(l.fusedTracks||[]).filter(t=>t.sourceCount>1).length;$('fusionAge').textContent=l.serverTimeMs?age(Date.now()-l.serverTimeMs):'—'}
function renderSensors(){const frame=currentFrame()||{clients:[]};const clients=frame.clients||[];$('sensorCount').textContent=clients.length+' online';$('sensors').innerHTML=clients.length?clients.map(c=>{const p=c.pose,tracking=String(p?.tracking||'UNLOCALIZED'),cls=tracking==='TRACKING'?'ok':p?'warn':'bad',st=c.status?.state||'connected';return '<div class="row"><span class="dot '+cls+'"></span><div class="name"><b>'+esc(short(c.clientId,18))+'</b><div class="tiny">'+esc(c.role||'participant')+' · '+esc(tracking)+'</div></div><div class="tiny">'+esc(st)+'</div></div>'}).join(''):'<span class="muted">No clients connected.</span>'}
function renderEntities(){const tracks=currentFrame()?.fusedTracks||[];$('entityCount').textContent=tracks.length;$('entities').innerHTML=tracks.length?tracks.map(t=>{const q=t.quality==='MULTI_SENSOR'?'multi':t.quality==='CONFLICT'?'conflict':'',sel=t.id===state.selectedId?' selected':'';return '<div class="entity'+sel+'" data-entity="'+esc(t.id)+'"><div class="entityHead"><span class="entityLabel">'+esc(t.label)+'</span><span class="mono tiny">'+esc(t.id)+'</span><span class="quality '+q+'">'+esc(t.quality||'SINGLE')+'</span></div><div class="entityMeta"><span>'+Math.round((t.confidence||0)*100)+'%</span><span>±'+fmt(t.uncertaintyMeters,2)+'m</span><span>'+Number(t.sourceCount||0)+' src</span><span>'+Math.round((t.agreement||0)*100)+'% agree</span></div></div>'}).join(''):'<span class="muted">No fused entities yet.</span>';document.querySelectorAll('[data-entity]').forEach(el=>el.onclick=()=>{state.selectedId=el.dataset.entity;renderEntities();renderInspector();draw()})}
function renderInspector(){const track=(currentFrame()?.fusedTracks||[]).find(t=>t.id===state.selectedId);if(!track){$('inspector').innerHTML='<span class="muted">Select a fused entity.</span>';return}const p=pos(track.position),v=pos(track.velocity);let html='<div class="kv"><div>ID</div><b class="mono">'+esc(track.id)+'</b><div>Class</div><b>'+esc(track.label)+'</b><div>Confidence</div><b>'+Math.round((track.confidence||0)*100)+'%</b><div>Agreement</div><b>'+Math.round((track.agreement||0)*100)+'%</b><div>Uncertainty</div><b>±'+fmt(track.uncertaintyMeters,2)+' m</b><div>Position XYZ</div><b class="mono">'+fmt(p[0])+' '+fmt(p[1])+' '+fmt(p[2])+'</b><div>Velocity</div><b class="mono">'+fmt(v[0])+' '+fmt(v[1])+' '+fmt(v[2])+'</b><div>Primary method</div><b>'+esc(track.primarySpatialMethod||'unknown')+'</b></div><div style="margin-top:10px" class="tiny">PROVENANCE</div>';for(const o of track.observations||[]){html+='<div class="obs"><div class="obsHead"><span class="sourceTag">'+esc(short(o.sourceId,16))+'</span><b>'+Math.round((o.confidence||0)*100)+'%</b><span class="tiny">±'+fmt(o.uncertaintyMeters,2)+'m</span></div><div class="tiny">'+esc(o.spatialMethod||'unknown')+' · hits '+Number(o.hitCount||0)+(o.depthConfidence==null?'':' · depth '+Math.round(o.depthConfidence*100)+'%')+'</div></div>'}$('inspector').innerHTML=html}
function renderMapFacts(){const f=currentFrame()?.fusion||{},m=state.map||{};$('mapFacts').innerHTML='<div>Anchors</div><b>'+Number(m.anchors?.length||0)+'</b><div>Scan points</div><b>'+Number(m.scan?.pointCount||0).toLocaleString()+'</b><div>Replay buffer</div><b>'+Number(f.replayFrameCount??state.history.length)+' frames</b>'}
function renderTimeline(){const slider=$('timeline'),frames=state.history;if(!frames.length){$('replayClock').textContent='--:--:--';$('timelineDetail').textContent='No replay frames yet';return}if(state.mode==='live'){state.replayIndex=frames.length-1;slider.value=state.replayIndex}const frame=frames[Math.max(0,Math.min(frames.length-1,state.replayIndex))];const d=new Date(frame.serverTimeMs);$('replayClock').textContent=d.toLocaleTimeString();$('oldest').textContent=new Date(frames[0].serverTimeMs).toLocaleTimeString();$('newest').textContent=new Date(frames[frames.length-1].serverTimeMs).toLocaleTimeString();$('timelineMode').textContent=state.mode==='live'?'LIVE SENSOR FUSION':'MISSION REPLAY';$('timelineDetail').textContent=(state.mode==='live'?'buffer ':'frame '+(state.replayIndex+1)+'/'+frames.length+' · ')+frames.length+' samples';$('modeChip').textContent=state.mode==='live'?'LIVE':'REPLAY';$('modeChip').className='chip '+(state.mode==='live'?'live':'');$('play').textContent=state.playing?'❚❚':'▶'}
function project(p,w,h){p=pos(p);const x=p[0]-state.center[0],y=p[1]-state.center[1],z=p[2]-state.center[2],c=Math.cos(state.yaw),s=Math.sin(state.yaw),rx=c*x-s*z,rz=s*x+c*z,scale=Math.min(w,h)*state.zoom/32;if(state.view==='top')return[w/2+rx*scale,h/2+rz*scale,scale];return[w/2+rx*scale,h/2+rz*scale*.56-y*scale*.72,scale]}
function draw(){const canvas=$('scene'),rect=canvas.getBoundingClientRect(),dpr=Math.max(1,Math.min(2,devicePixelRatio||1));if(canvas.width!==Math.round(rect.width*dpr)||canvas.height!==Math.round(rect.height*dpr)){canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr)}const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);const w=rect.width,h=rect.height;ctx.clearRect(0,0,w,h);drawGrid(ctx,w,h);const frame=currentFrame()||{};if(state.layers.points)drawPoints(ctx,w,h);if(state.layers.trails)drawTrails(ctx,w,h);if(state.layers.anchors)drawAnchors(ctx,w,h);if(state.layers.links)drawLinks(ctx,w,h,frame);if(state.layers.clients)drawClients(ctx,w,h,frame);if(state.layers.tracks)drawTracks(ctx,w,h,frame);const fusion=frame.fusion||{};$('sceneHud').textContent=(state.mode==='live'?'LIVE':'REPLAY')+' · '+Number(fusion.connectedClientCount??frame.clients?.length??0)+' sensors · '+Number(fusion.rawObservationCount??frame.rawTrackCount??frame.tracks?.length??0)+' observations → '+Number(fusion.fusedEntityCount??frame.fusedTracks?.length??0)+' entities · drag rotate · wheel zoom'}
function drawGrid(ctx,w,h){ctx.save();ctx.strokeStyle='#142029';ctx.lineWidth=1;const step=60;for(let x=(w/2)%step;x<w;x+=step){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=(h/2)%step;y<h;y+=step){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.restore()}
function drawPoints(ctx,w,h){const pts=state.cloud?.points||[];if(!pts.length)return;const stride=Math.max(1,Math.ceil(pts.length/14000)),bounds=state.cloud?.bounds,minY=bounds?.min?.[1]??-1,maxY=bounds?.max?.[1]??1,span=Math.max(.1,maxY-minY);ctx.save();for(let i=0;i<pts.length;i+=stride){const p=pts[i],q=Number(p[3]??.3);if(q<.18)continue;const pr=project(p,w,h),t=Math.max(0,Math.min(1,(p[1]-minY)/span));ctx.fillStyle='hsla('+(165+45*t)+',55%,'+(42+18*t)+'%,'+(0.12+0.38*Math.min(1,q))+')';ctx.fillRect(pr[0],pr[1],1.3,1.3)}ctx.restore()}
function drawAnchors(ctx,w,h){const anchors=state.map?.anchors||[];ctx.save();ctx.font='9px ui-monospace,monospace';for(const a of anchors){const p=project(matrixPos(a.siteFromAnchor),w,h),good=a.featureQuality==='GOOD',suff=a.featureQuality==='SUFFICIENT';ctx.strokeStyle=good?'#72e390':suff?'#f2b653':'#7f929e';ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.moveTo(p[0],p[1]-5);ctx.lineTo(p[0]+5,p[1]);ctx.lineTo(p[0],p[1]+5);ctx.lineTo(p[0]-5,p[1]);ctx.closePath();ctx.stroke();if(state.layers.labels)ctx.fillText('A '+short(a.id,11)+' '+String(a.featureQuality||''),p[0]+8,p[1]+3)}ctx.restore()}
function drawClients(ctx,w,h,frame){ctx.save();ctx.font='10px ui-monospace,monospace';for(const c of frame.clients||[]){if(!c.pose?.position)continue;const p=project(c.pose.position,w,h),forward=rotateQuat([0,0,-1],c.pose.rotation),fp=project([c.pose.position[0]+forward[0]*.8,c.pose.position[1]+forward[1]*.8,c.pose.position[2]+forward[2]*.8],w,h);ctx.strokeStyle='#4fe1d2';ctx.fillStyle='#4fe1d2';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(p[0],p[1],4,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(p[0],p[1]);ctx.lineTo(fp[0],fp[1]);ctx.stroke();if(state.layers.labels)ctx.fillText('S '+short(c.clientId,13),p[0]+7,p[1]-7)}ctx.restore()}
function drawLinks(ctx,w,h,frame){const clients=new Map((frame.clients||[]).filter(c=>c.pose?.position).map(c=>[c.clientId,c]));ctx.save();ctx.setLineDash([3,5]);for(const t of frame.fusedTracks||[]){const tp=project(t.position,w,h);for(const sid of t.sourceIds||[]){const c=clients.get(sid);if(!c)continue;const cp=project(c.pose.position,w,h);ctx.strokeStyle=t.sourceCount>1?'rgba(114,227,144,.35)':'rgba(79,225,210,.18)';ctx.beginPath();ctx.moveTo(cp[0],cp[1]);ctx.lineTo(tp[0],tp[1]);ctx.stroke()}}ctx.restore()}
function drawTracks(ctx,w,h,frame){ctx.save();ctx.font='10px ui-monospace,monospace';for(const t of frame.fusedTracks||[]){const p=project(t.position,w,h),selected=t.id===state.selectedId,multi=t.quality==='MULTI_SENSOR',conflict=t.quality==='CONFLICT',color=conflict?'#ff6f68':multi?'#72e390':'#f2b653';if(state.layers.uncertainty){const px2=project([t.position[0]+(t.uncertaintyMeters||.5),t.position[1],t.position[2]],w,h),r=Math.max(4,Math.abs(px2[0]-p[0]));ctx.strokeStyle=color+'55';ctx.beginPath();ctx.arc(p[0],p[1],r,0,Math.PI*2);ctx.stroke()}ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=selected?3:1.8;if(t.label==='car'){const ex=Math.max(8,(t.extentMeters?.[0]||1.8)*p[2]),ez=Math.max(12,(t.extentMeters?.[2]||4)*p[2]*.45);ctx.save();ctx.translate(p[0],p[1]);ctx.rotate(-(t.yawRadians||0)-state.yaw);ctx.strokeRect(-ex/2,-ez/2,ex,ez);ctx.restore()}else{ctx.beginPath();ctx.arc(p[0],p[1],t.label==='person'?6:5,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(p[0]-4,p[1]);ctx.lineTo(p[0]+4,p[1]);ctx.moveTo(p[0],p[1]-4);ctx.lineTo(p[0],p[1]+4);ctx.stroke()}if(state.layers.labels){ctx.fillText(String(t.label).toUpperCase()+' '+short(t.id,10)+' '+Math.round((t.confidence||0)*100)+'% · '+Number(t.sourceCount||0)+'S',p[0]+8,p[1]-9)}}ctx.restore()}
function drawTrails(ctx,w,h){if(!state.history.length)return;const byId=new Map();for(const frame of state.history){for(const t of frame.fusedTracks||[]){let a=byId.get(t.id);if(!a)byId.set(t.id,a=[]);a.push(t.position)}}ctx.save();ctx.strokeStyle='rgba(108,169,255,.28)';ctx.lineWidth=1.2;for(const pts of byId.values()){if(pts.length<2)continue;ctx.beginPath();pts.forEach((p,i)=>{const q=project(p,w,h);if(i===0)ctx.moveTo(q[0],q[1]);else ctx.lineTo(q[0],q[1])});ctx.stroke()}ctx.restore()}
$('ownerAccess').onclick=()=>{$('authGate').classList.remove('hidden');$('token').focus()};$('closeAuth').onclick=()=>$('authGate').classList.add('hidden');$('connect').onclick=()=>connectOwner(false);$('worldDebugger').onclick=()=>location.href='/';$('mapSelect').onchange=async e=>{state.map=state.maps.find(m=>m.id===e.target.value)||null;await loadMap()};
$('viewIso').onclick=()=>{state.view='iso';$('viewIso').classList.add('active');$('viewTop').classList.remove('active');draw()};$('viewTop').onclick=()=>{state.view='top';$('viewTop').classList.add('active');$('viewIso').classList.remove('active');draw()};$('fit').onclick=()=>{fitView();draw()};$('liveNow').onclick=jumpLive;$('jumpLive').onclick=jumpLive;
function jumpLive(){state.mode='live';state.playing=false;renderAll()}
$('timeline').oninput=e=>{state.mode='replay';state.playing=false;state.replayIndex=Number(e.target.value)||0;renderAll()};$('play').onclick=()=>{if(!state.history.length)return;state.mode='replay';state.playing=!state.playing;renderTimeline()};
document.querySelectorAll('[data-layer]').forEach(el=>el.onchange=()=>{state.layers[el.dataset.layer]=el.checked;draw()});
const canvas=$('scene');canvas.onpointerdown=e=>{state.drag={x:e.clientX,y:e.clientY,yaw:state.yaw};canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!state.drag)return;state.yaw=state.drag.yaw+(e.clientX-state.drag.x)*.006;draw()};canvas.onpointerup=()=>state.drag=null;canvas.onwheel=e=>{e.preventDefault();state.zoom=Math.max(.15,Math.min(8,state.zoom*Math.exp(-e.deltaY*.001)));draw()};
setInterval(()=>{if(state.playing&&state.history.length){state.replayIndex=Math.min(state.history.length-1,state.replayIndex+1);if(state.replayIndex>=state.history.length-1)state.playing=false;$('timeline').value=state.replayIndex;renderAll()}},500);
setInterval(()=>{if(state.map)refreshLive()},500);setInterval(()=>{if(state.map)refreshReplay()},4000);window.addEventListener('resize',draw);discover();
</script>
</body>
</html>`;
}
